"""empty message

Revision ID: 02533cebd7c9
Revises: 
Create Date: 2026-01-28 12:03:11.412670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02533cebd7c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    addresstype_enum = sa.Enum('Primary', 'Secondary', name='addresstype')
    addresstype_enum.create(op.get_bind(), checkfirst=True)
    
    # Alter the column to use the enum type
    op.alter_column('addresses', 'address_type',
               existing_type=sa.VARCHAR(),
               type_=addresstype_enum,
               nullable=False,
               postgresql_using='address_type::addresstype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter the column back to VARCHAR
    op.alter_column('addresses', 'address_type',
               existing_type=sa.Enum('Primary', 'Secondary', name='addresstype'),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='address_type::text')
    
    # Drop the enum type
    sa.Enum(name='addresstype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
