"""creted assets_disclosure_documents table

Revision ID: 03217bacbe96
Revises: b1911cf08f25
Create Date: 2026-01-09 14:41:16.629374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03217bacbe96'
down_revision: Union[str, Sequence[str], None] = 'b1911cf08f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_disclosure_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash', 'financial_year_id', name='uq_assets_doc_client_hash')
    )
    op.create_index(op.f('ix_assets_disclosure_documents_financial_year_id'), 'assets_disclosure_documents', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_assets_disclosure_documents_id'), 'assets_disclosure_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_disclosure_documents_id'), table_name='assets_disclosure_documents')
    op.drop_index(op.f('ix_assets_disclosure_documents_financial_year_id'), table_name='assets_disclosure_documents')
    op.drop_table('assets_disclosure_documents')
    # ### end Alembic commands ###
