"""empty message

Revision ID: 06b8a01d8633
Revises: d011c094f129
Create Date: 2025-12-27 13:58:32.501618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b8a01d8633'
down_revision: Union[str, Sequence[str], None] = 'd011c094f129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_signing_authority_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code_of_institution', sa.String(), nullable=True),
    sa.Column('name_of_account_holder', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('peak_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_accrued_taxable', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_accrued_in_account', sa.Boolean(), nullable=True),
    sa.Column('amount_taxed_on_income', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_signing_authority_accounts_country_id'), 'foreign_signing_authority_accounts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_signing_authority_accounts_financial_year_id'), 'foreign_signing_authority_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_signing_authority_accounts_id'), 'foreign_signing_authority_accounts', ['id'], unique=False)
    op.add_column('addresses', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('addresses_client_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('addresses', 'client_id')
    op.add_column('assets_with_maturity', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('assets_with_maturity_client_id_fkey'), 'assets_with_maturity', type_='foreignkey')
    op.create_foreign_key(None, 'assets_with_maturity', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('assets_with_maturity', 'client_id')
    op.add_column('call_logs', sa.Column('caller_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_call_logs_from_number'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_to_number'), table_name='call_logs')
    op.add_column('children_info', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('children_info_client_id_fkey'), 'children_info', type_='foreignkey')
    op.create_foreign_key(None, 'children_info', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('children_info', 'client_id')
    op.add_column('cp_advisors', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('cp_advisors_client_id_fkey'), 'cp_advisors', type_='foreignkey')
    op.create_foreign_key(None, 'cp_advisors', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cp_advisors', 'client_id')
    op.add_column('employment', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('employment_client_id_fkey'), 'employment', type_='foreignkey')
    op.create_foreign_key(None, 'employment', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employment', 'client_id')
    op.add_column('foreign_depository_accounts', sa.Column('name_of_institution', sa.String(), nullable=True))
    op.add_column('foreign_depository_accounts', sa.Column('address_of_institution', sa.String(), nullable=True))
    op.add_column('foreign_depository_accounts', sa.Column('zip_code_of_institution', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('goals_client_id_fkey'), 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('goals', 'client_id')
    op.add_column('insurance', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('insurance_client_id_fkey'), 'insurance', type_='foreignkey')
    op.create_foreign_key(None, 'insurance', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('insurance', 'client_id')
    op.add_column('loan_records', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('loan_records_client_id_fkey'), 'loan_records', type_='foreignkey')
    op.create_foreign_key(None, 'loan_records', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('loan_records', 'client_id')
    op.add_column('other_assets', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('other_assets_client_id_fkey'), 'other_assets', type_='foreignkey')
    op.create_foreign_key(None, 'other_assets', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('other_assets', 'client_id')
    op.add_column('other_loans', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('other_loans_client_id_fkey'), 'other_loans', type_='foreignkey')
    op.create_foreign_key(None, 'other_loans', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('other_loans', 'client_id')
    op.add_column('parent_assets', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('parent_assets_client_id_fkey'), 'parent_assets', type_='foreignkey')
    op.create_foreign_key(None, 'parent_assets', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('parent_assets', 'client_id')
    op.add_column('real_estate_plans', sa.Column('client_profile_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('real_estate_plans_client_id_fkey'), 'real_estate_plans', type_='foreignkey')
    op.create_foreign_key(None, 'real_estate_plans', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('real_estate_plans', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_estate_plans', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'real_estate_plans', type_='foreignkey')
    op.create_foreign_key(op.f('real_estate_plans_client_id_fkey'), 'real_estate_plans', 'clients', ['client_id'], ['id'])
    op.drop_column('real_estate_plans', 'client_profile_id')
    op.add_column('parent_assets', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parent_assets', type_='foreignkey')
    op.create_foreign_key(op.f('parent_assets_client_id_fkey'), 'parent_assets', 'clients', ['client_id'], ['id'])
    op.drop_column('parent_assets', 'client_profile_id')
    op.add_column('other_loans', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'other_loans', type_='foreignkey')
    op.create_foreign_key(op.f('other_loans_client_id_fkey'), 'other_loans', 'clients', ['client_id'], ['id'])
    op.drop_column('other_loans', 'client_profile_id')
    op.add_column('other_assets', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'other_assets', type_='foreignkey')
    op.create_foreign_key(op.f('other_assets_client_id_fkey'), 'other_assets', 'clients', ['client_id'], ['id'])
    op.drop_column('other_assets', 'client_profile_id')
    op.add_column('loan_records', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'loan_records', type_='foreignkey')
    op.create_foreign_key(op.f('loan_records_client_id_fkey'), 'loan_records', 'clients', ['client_id'], ['id'])
    op.drop_column('loan_records', 'client_profile_id')
    op.add_column('insurance', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'insurance', type_='foreignkey')
    op.create_foreign_key(op.f('insurance_client_id_fkey'), 'insurance', 'clients', ['client_id'], ['id'])
    op.drop_column('insurance', 'client_profile_id')
    op.add_column('goals', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key(op.f('goals_client_id_fkey'), 'goals', 'clients', ['client_id'], ['id'])
    op.drop_column('goals', 'client_profile_id')
    op.drop_column('foreign_depository_accounts', 'zip_code_of_institution')
    op.drop_column('foreign_depository_accounts', 'address_of_institution')
    op.drop_column('foreign_depository_accounts', 'name_of_institution')
    op.add_column('employment', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employment', type_='foreignkey')
    op.create_foreign_key(op.f('employment_client_id_fkey'), 'employment', 'clients', ['client_id'], ['id'])
    op.drop_column('employment', 'client_profile_id')
    op.add_column('cp_advisors', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cp_advisors', type_='foreignkey')
    op.create_foreign_key(op.f('cp_advisors_client_id_fkey'), 'cp_advisors', 'clients', ['client_id'], ['id'])
    op.drop_column('cp_advisors', 'client_profile_id')
    op.add_column('children_info', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'children_info', type_='foreignkey')
    op.create_foreign_key(op.f('children_info_client_id_fkey'), 'children_info', 'clients', ['client_id'], ['id'])
    op.drop_column('children_info', 'client_profile_id')
    op.create_index(op.f('ix_call_logs_to_number'), 'call_logs', ['to_number'], unique=False)
    op.create_index(op.f('ix_call_logs_from_number'), 'call_logs', ['from_number'], unique=False)
    op.drop_column('call_logs', 'caller_name')
    op.add_column('assets_with_maturity', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assets_with_maturity', type_='foreignkey')
    op.create_foreign_key(op.f('assets_with_maturity_client_id_fkey'), 'assets_with_maturity', 'clients', ['client_id'], ['id'])
    op.drop_column('assets_with_maturity', 'client_profile_id')
    op.add_column('addresses', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_client_id_fkey'), 'addresses', 'clients', ['client_id'], ['id'])
    op.drop_column('addresses', 'client_profile_id')
    op.drop_index(op.f('ix_foreign_signing_authority_accounts_id'), table_name='foreign_signing_authority_accounts')
    op.drop_index(op.f('ix_foreign_signing_authority_accounts_financial_year_id'), table_name='foreign_signing_authority_accounts')
    op.drop_index(op.f('ix_foreign_signing_authority_accounts_country_id'), table_name='foreign_signing_authority_accounts')
    op.drop_table('foreign_signing_authority_accounts')
    # ### end Alembic commands ###
