"""empty message

Revision ID: 09329e8f3cd9
Revises: bb07d756c5f5
Create Date: 2025-12-06 13:13:49.459557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09329e8f3cd9'
down_revision: Union[str, Sequence[str], None] = 'bb07d756c5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_resource_requested', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('activation_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_is_active'), 'tasks', ['is_active'], unique=False)
    op.drop_column('tasks', 'is_resource_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_resource_request', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_is_active'), table_name='tasks')
    op.drop_column('tasks', 'activation_time')
    op.drop_column('tasks', 'is_active')
    op.drop_column('tasks', 'is_resource_requested')
    # ### end Alembic commands ###
