"""empty message

Revision ID: 1ba1b8b58441
Revises: bd64924356ee
Create Date: 2025-11-13 18:24:40.883205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ba1b8b58441'
down_revision: Union[str, Sequence[str], None] = 'bd64924356ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subCategory', sa.String(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('is_password_protected', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_upload_id'), 'documents_upload', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assigner_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('is_parent_task', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('acceptance_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='acceptance_status', native_enum=False), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rejection_by', sa.Uuid(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejection_by'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'advisor_id')
    )
    op.create_table('task_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_by', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('file_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_chat_messages_sender_id'), 'task_chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_task_chat_messages_task_id'), 'task_chat_messages', ['task_id'], unique=False)
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_login_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_otp'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.add_column('capital_gains', sa.Column('shortTermLossCarryForward', sa.Float(), nullable=True))
    op.add_column('capital_gains', sa.Column('longTermLossCarryForward', sa.Float(), nullable=True))
    op.add_column('other_income', sa.Column('tds_on_capital_gains', sa.Float(), nullable=True))
    op.add_column('tax_profile', sa.Column('advance_tax_paid_Q1', sa.Float(), nullable=True))
    op.add_column('tax_profile', sa.Column('advance_tax_paid_Q2', sa.Float(), nullable=True))
    op.add_column('tax_profile', sa.Column('advance_tax_paid_Q3', sa.Float(), nullable=True))
    op.add_column('tax_profile', sa.Column('advance_tax_paid_Q4', sa.Float(), nullable=True))
    op.drop_column('tax_profile', 'previous_year_income')
    op.drop_column('tax_profile', 'advance_tax_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_profile', sa.Column('advance_tax_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('tax_profile', sa.Column('previous_year_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tax_profile', 'advance_tax_paid_Q4')
    op.drop_column('tax_profile', 'advance_tax_paid_Q3')
    op.drop_column('tax_profile', 'advance_tax_paid_Q2')
    op.drop_column('tax_profile', 'advance_tax_paid_Q1')
    op.drop_column('other_income', 'tds_on_capital_gains')
    op.drop_column('capital_gains', 'longTermLossCarryForward')
    op.drop_column('capital_gains', 'shortTermLossCarryForward')
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('login_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('unique_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['logins.id'], name=op.f('otp_verifications_login_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_verifications_pkey'))
    )
    op.create_index(op.f('ix_otp_verifications_otp'), 'otp_verifications', ['otp'], unique=True)
    op.create_index(op.f('ix_otp_verifications_login_id'), 'otp_verifications', ['login_id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.drop_index(op.f('ix_task_chat_messages_task_id'), table_name='task_chat_messages')
    op.drop_index(op.f('ix_task_chat_messages_sender_id'), table_name='task_chat_messages')
    op.drop_table('task_chat_messages')
    op.drop_table('task_assignees')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_documents_upload_id'), table_name='documents_upload')
    op.drop_table('documents_upload')
    # ### end Alembic commands ###
