"""added pause_reason in task table

Revision ID: 48e0cd8358f8
Revises: d033ec827c14
Create Date: 2025-12-05 16:59:30.141281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48e0cd8358f8'
down_revision: Union[str, Sequence[str], None] = 'd033ec827c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('pause_reason', sa.String(), nullable=True))
    op.add_column('tax_profile', sa.Column('gross_salary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tax_profile', sa.Column('tds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_profile', 'tds')
    op.drop_column('tax_profile', 'gross_salary')
    op.drop_column('tasks', 'pause_reason')
    # ### end Alembic commands ###
