"""Updated file table

Revision ID: 4af53c07ff47
Revises: a2926a2ba386
Create Date: 2025-11-28 13:14:41.896822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af53c07ff47'
down_revision: Union[str, Sequence[str], None] = 'a2926a2ba386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_details', sa.Column('foreign_interest', sa.Float(), nullable=True))
    op.add_column('interest_details', sa.Column('foreign_interest_ftc', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'client_id')
    op.drop_column('interest_details', 'foreign_interest_ftc')
    op.drop_column('interest_details', 'foreign_interest')
    # ### end Alembic commands ###
