"""New Table for files

Revision ID: 4b3993796c67
Revises: 1ba1b8b58441
Create Date: 2025-11-25 12:09:10.574663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b3993796c67'
down_revision: Union[str, Sequence[str], None] = '1ba1b8b58441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advisors', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('advisors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('capital_gains', sa.Column('cryptoCaptialGains', sa.Float(), nullable=True))
    op.alter_column('clients', 'adhar_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'pan_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('clients', 'family_relationship',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'residence_type',
               existing_type=postgresql.ENUM('RES', 'NORES', 'RNOR', name='residencetype'),
               nullable=True)
    op.drop_constraint(op.f('clients_adhar_number_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_pan_number_key'), 'clients', type_='unique')
    op.alter_column('logins', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logins', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tasks', sa.Column('file_uploads', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'file_uploads')
    op.alter_column('logins', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logins', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('clients_pan_number_key'), 'clients', ['pan_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_adhar_number_key'), 'clients', ['adhar_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'residence_type',
               existing_type=postgresql.ENUM('RES', 'NORES', 'RNOR', name='residencetype'),
               nullable=False)
    op.alter_column('clients', 'family_relationship',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('clients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'pan_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'adhar_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('capital_gains', 'cryptoCaptialGains')
    op.alter_column('advisors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('advisors', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
