"""empty message

Revision ID: 4e55d281118c
Revises: 11029de5a3ce
Create Date: 2026-01-06 11:46:01.249844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e55d281118c'
down_revision: Union[str, Sequence[str], None] = '11029de5a3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_deposit_custodial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('account_opened_during_tax_year', sa.Boolean(), nullable=True),
    sa.Column('account_closed_during_tax_year', sa.Boolean(), nullable=True),
    sa.Column('account_jointly_owned_with_spouse', sa.Boolean(), nullable=True),
    sa.Column('no_tax_item_reported', sa.Boolean(), nullable=True),
    sa.Column('maximum_value_during_tax_year', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('used_foreign_currency_exchange_rate', sa.Boolean(), nullable=True),
    sa.Column('foreign_currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('exchange_rate_source', sa.String(), nullable=True),
    sa.Column('name_of_financial_institution', sa.String(), nullable=True),
    sa.Column('giin', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('city_state_country_zip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_deposit_custodial_accounts_financial_year_id'), 'foreign_deposit_custodial_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_deposit_custodial_accounts_id'), 'foreign_deposit_custodial_accounts', ['id'], unique=False)
    op.add_column('country_lookup', sa.Column('iso_country_code', sa.String(), nullable=True))
    op.add_column('country_lookup', sa.Column('numeric_country_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_country_lookup_iso_country_code'), 'country_lookup', ['iso_country_code'], unique=False)
    op.create_index(op.f('ix_country_lookup_numeric_country_code'), 'country_lookup', ['numeric_country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_lookup_numeric_country_code'), table_name='country_lookup')
    op.drop_index(op.f('ix_country_lookup_iso_country_code'), table_name='country_lookup')
    op.drop_column('country_lookup', 'numeric_country_code')
    op.drop_column('country_lookup', 'iso_country_code')
    op.drop_index(op.f('ix_foreign_deposit_custodial_accounts_id'), table_name='foreign_deposit_custodial_accounts')
    op.drop_index(op.f('ix_foreign_deposit_custodial_accounts_financial_year_id'), table_name='foreign_deposit_custodial_accounts')
    op.drop_table('foreign_deposit_custodial_accounts')
    # ### end Alembic commands ###
