"""empty message

Revision ID: 4ff9274dd86f
Revises: 
Create Date: 2026-01-30 18:44:13.592796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff9274dd86f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizenships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('citizenship', sa.String(length=255), nullable=True),
    sa.Column('citizenship_start_date', sa.Date(), nullable=True),
    sa.Column('citizenship_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizenships_id'), 'citizenships', ['id'], unique=False)
    op.create_table('insurances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('sum_assured', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('premium_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('annuity_plan', sa.Boolean(), nullable=False),
    sa.Column('annuity_receivable', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annuity_receivable_start_date', sa.Date(), nullable=True),
    sa.Column('annuity_receivable_end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurances_id'), 'insurances', ['id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('lender_issuer', sa.String(length=255), nullable=True),
    sa.Column('principal_outstanding', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('emi', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('owners_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_table('personal_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('social_security_number', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('power_of_attorney', sa.Boolean(), nullable=True),
    sa.Column('is_huf', sa.String(), nullable=True),
    sa.Column('huf_pan', sa.String(), nullable=True),
    sa.Column('huf_dob', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_personal_information_id'), 'personal_information', ['id'], unique=False)
    op.create_table('residencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('residency', sa.String(length=255), nullable=True),
    sa.Column('residency_start_date', sa.Date(), nullable=True),
    sa.Column('residency_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residencies_id'), 'residencies', ['id'], unique=False)
    op.drop_index(op.f('ix_rsu_vesting_financial_year_id'), table_name='rsu_vesting')
    op.drop_index(op.f('ix_rsu_vesting_id'), table_name='rsu_vesting')
    op.drop_table('rsu_vesting')
    op.drop_index(op.f('ix_assets_with_maturity_id'), table_name='assets_with_maturity')
    op.drop_table('assets_with_maturity')
    op.drop_index(op.f('ix_cash_flows_financial_year_id'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_cash_flow_office_financial_year_id'), table_name='cash_flow_office')
    op.drop_index(op.f('ix_cash_flow_office_id'), table_name='cash_flow_office')
    op.drop_table('cash_flow_office')
    op.drop_index(op.f('ix_real_estate_plans_id'), table_name='real_estate_plans')
    op.drop_table('real_estate_plans')
    op.drop_index(op.f('ix_incomes_financial_year_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_other_loans_id'), table_name='other_loans')
    op.drop_table('other_loans')
    op.drop_index(op.f('ix_cp_advisors_id'), table_name='cp_advisors')
    op.drop_table('cp_advisors')
    op.drop_index(op.f('ix_loan_records_id'), table_name='loan_records')
    op.drop_table('loan_records')
    op.drop_index(op.f('ix_soa_master_financial_year_id'), table_name='soa_master')
    op.drop_index(op.f('ix_soa_master_id'), table_name='soa_master')
    op.drop_table('soa_master')
    op.drop_index(op.f('ix_parent_assets_id'), table_name='parent_assets')
    op.drop_table('parent_assets')
    op.drop_index(op.f('ix_children_info_id'), table_name='children_info')
    op.drop_table('children_info')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_client_profiles_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_tax_records_financial_year_id'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_id'), table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_insurance_id'), table_name='insurance')
    op.drop_table('insurance')
    op.drop_index(op.f('ix_other_assets_id'), table_name='other_assets')
    op.drop_table('other_assets')
    op.add_column('addresses', sa.Column('client_id', sa.UUID(), nullable=False))
    op.alter_column('addresses', 'address_type',
               existing_type=postgresql.ENUM('Primary', 'Secondary', name='addresstype'),
               type_=sa.Enum('PRIMARY', 'SECONDARY', name='addresstype', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('addresses_client_profile_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('addresses', 'client_profile_id')
    op.add_column('assets_disclosure_documents', sa.Column('is_reviewed', sa.Boolean(), server_default='FALSE', nullable=False))
    op.drop_constraint(op.f('assets_disclosure_documents_financial_year_id_fkey'), 'assets_disclosure_documents', type_='foreignkey')
    op.create_foreign_key(None, 'assets_disclosure_documents', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('capital_gains_quarter_id_fkey'), 'capital_gains', type_='foreignkey')
    op.create_foreign_key(None, 'capital_gains', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('comments_quarter_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dividends_quarter_id_fkey'), 'dividends', type_='foreignkey')
    op.create_foreign_key(None, 'dividends', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.add_column('employment', sa.Column('client_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('employment_client_profile_id_fkey'), 'employment', type_='foreignkey')
    op.create_foreign_key(None, 'employment', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employment', 'end_date')
    op.drop_column('employment', 'start_date')
    op.drop_column('employment', 'client_profile_id')
    op.drop_constraint(op.f('financial_years_client_id_fkey'), 'financial_years', type_='foreignkey')
    op.create_foreign_key(None, 'financial_years', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_custodial_accounts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_custodial_accounts_financial_year_id_fkey'), 'foreign_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_deposit_custodial_accounts', sa.Column('hash_key', sa.String(), nullable=True))
    op.add_column('foreign_deposit_custodial_accounts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_deposit_custodial_accounts_financial_year_id_fkey'), 'foreign_deposit_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_deposit_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_depository_accounts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_depository_accounts_financial_year_id_fkey'), 'foreign_depository_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_depository_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_equity_debt_interests', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_equity_debt_interests_financial_year_id_fkey'), 'foreign_equity_debt_interests', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_equity_debt_interests', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_financial_interests', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_financial_interests_financial_year_id_fkey'), 'foreign_financial_interests', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_financial_interests', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_immovable_properties', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_immovable_properties_financial_year_id_fkey'), 'foreign_immovable_properties', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_immovable_properties', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_insurance_contracts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_insurance_contracts_financial_year_id_fkey'), 'foreign_insurance_contracts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_insurance_contracts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_other_capital_assets', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_other_capital_assets_financial_year_id_fkey'), 'foreign_other_capital_assets', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_other_capital_assets', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_other_incomes', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_other_incomes_financial_year_id_fkey'), 'foreign_other_incomes', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_other_incomes', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('foreign_signing_authority_accounts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('foreign_signing_authority_accounts_financial_year_id_fkey'), 'foreign_signing_authority_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_signing_authority_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interest_details_quarter_id_fkey'), 'interest_details', type_='foreignkey')
    op.create_foreign_key(None, 'interest_details', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.add_column('jointly_owned_accounts', sa.Column('hash_key', sa.String(), nullable=True))
    op.add_column('jointly_owned_accounts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('jointly_owned_accounts_financial_year_id_fkey'), 'jointly_owned_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'jointly_owned_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('logins_client_id_fkey'), 'logins', type_='foreignkey')
    op.create_foreign_key(None, 'logins', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('other_income_quarter_id_fkey'), 'other_income', type_='foreignkey')
    op.create_foreign_key(None, 'other_income', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quarters_financial_year_id_fkey'), 'quarters', type_='foreignkey')
    op.create_foreign_key(None, 'quarters', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('real_estate', sa.Column('client_id', sa.UUID(), nullable=False))
    op.add_column('real_estate', sa.Column('property_type', sa.String(), nullable=True))
    op.add_column('real_estate', sa.Column('estimated_value', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('real_estate', sa.Column('year_of_acquisition', sa.Integer(), nullable=True))
    op.add_column('real_estate', sa.Column('state', sa.String(), nullable=True))
    op.add_column('real_estate', sa.Column('country', sa.String(), nullable=True))
    op.add_column('real_estate', sa.Column('loan_closed', sa.Boolean(), nullable=True))
    op.add_column('real_estate', sa.Column('loan_starting_date', sa.Date(), nullable=True))
    op.add_column('real_estate', sa.Column('outStanding_loan_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('real_estate', sa.Column('interest_rate', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('real_estate', sa.Column('emi_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('real_estate', sa.Column('rent_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('real_estate', sa.Column('property_tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('real_estate', sa.Column('insured', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('real_estate', sa.Column('insured_details', sa.Text(), nullable=True))
    op.alter_column('real_estate', 'owners',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('real_estate', 'loan_attached',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('real_estate', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('real_estate', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_real_estate_financial_year_id'), table_name='real_estate')
    op.create_index(op.f('ix_real_estate_client_id'), 'real_estate', ['client_id'], unique=False)
    op.drop_constraint(op.f('real_estate_financial_year_id_fkey'), 'real_estate', type_='foreignkey')
    op.create_foreign_key(None, 'real_estate', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('real_estate', 'financial_year_id')
    op.drop_column('real_estate', 'usage_type')
    op.drop_column('real_estate', 'details')
    op.drop_column('real_estate', 'market_value')
    op.drop_column('real_estate', 'state_country')
    op.drop_constraint(op.f('rentals_quarter_id_fkey'), 'rentals', type_='foreignkey')
    op.create_foreign_key(None, 'rentals', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.add_column('separately_owned_accounts', sa.Column('hash_key', sa.String(), nullable=True))
    op.add_column('separately_owned_accounts', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint(op.f('separately_owned_accounts_financial_year_id_fkey'), 'separately_owned_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'separately_owned_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_client_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tax_profile_financial_year_id_fkey'), 'tax_profile', type_='foreignkey')
    op.drop_constraint(op.f('tax_profile_client_id_fkey'), 'tax_profile', type_='foreignkey')
    op.create_foreign_key(None, 'tax_profile', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tax_profile', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tax_profile', type_='foreignkey')
    op.drop_constraint(None, 'tax_profile', type_='foreignkey')
    op.create_foreign_key(op.f('tax_profile_client_id_fkey'), 'tax_profile', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('tax_profile_financial_year_id_fkey'), 'tax_profile', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_client_id_fkey'), 'tasks', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'separately_owned_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('separately_owned_accounts_financial_year_id_fkey'), 'separately_owned_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('separately_owned_accounts', 'comment')
    op.drop_column('separately_owned_accounts', 'hash_key')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.create_foreign_key(op.f('rentals_quarter_id_fkey'), 'rentals', 'quarters', ['quarter_id'], ['id'])
    op.add_column('real_estate', sa.Column('state_country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('real_estate', sa.Column('market_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('real_estate', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('real_estate', sa.Column('usage_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('real_estate', sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'real_estate', type_='foreignkey')
    op.create_foreign_key(op.f('real_estate_financial_year_id_fkey'), 'real_estate', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_index(op.f('ix_real_estate_client_id'), table_name='real_estate')
    op.create_index(op.f('ix_real_estate_financial_year_id'), 'real_estate', ['financial_year_id'], unique=False)
    op.alter_column('real_estate', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('real_estate', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('real_estate', 'loan_attached',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('real_estate', 'owners',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('real_estate', 'insured_details')
    op.drop_column('real_estate', 'insured')
    op.drop_column('real_estate', 'property_tax_amount')
    op.drop_column('real_estate', 'rent_amount')
    op.drop_column('real_estate', 'emi_amount')
    op.drop_column('real_estate', 'interest_rate')
    op.drop_column('real_estate', 'outStanding_loan_amount')
    op.drop_column('real_estate', 'loan_starting_date')
    op.drop_column('real_estate', 'loan_closed')
    op.drop_column('real_estate', 'country')
    op.drop_column('real_estate', 'state')
    op.drop_column('real_estate', 'year_of_acquisition')
    op.drop_column('real_estate', 'estimated_value')
    op.drop_column('real_estate', 'property_type')
    op.drop_column('real_estate', 'client_id')
    op.drop_constraint(None, 'quarters', type_='foreignkey')
    op.create_foreign_key(op.f('quarters_financial_year_id_fkey'), 'quarters', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'other_income', type_='foreignkey')
    op.create_foreign_key(op.f('other_income_quarter_id_fkey'), 'other_income', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'logins', type_='foreignkey')
    op.create_foreign_key(op.f('logins_client_id_fkey'), 'logins', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'jointly_owned_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('jointly_owned_accounts_financial_year_id_fkey'), 'jointly_owned_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('jointly_owned_accounts', 'comment')
    op.drop_column('jointly_owned_accounts', 'hash_key')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.create_foreign_key(op.f('interest_details_quarter_id_fkey'), 'interest_details', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'foreign_signing_authority_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_signing_authority_accounts_financial_year_id_fkey'), 'foreign_signing_authority_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_signing_authority_accounts', 'comment')
    op.drop_constraint(None, 'foreign_other_incomes', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_other_incomes_financial_year_id_fkey'), 'foreign_other_incomes', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_other_incomes', 'comment')
    op.drop_constraint(None, 'foreign_other_capital_assets', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_other_capital_assets_financial_year_id_fkey'), 'foreign_other_capital_assets', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_other_capital_assets', 'comment')
    op.drop_constraint(None, 'foreign_insurance_contracts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_insurance_contracts_financial_year_id_fkey'), 'foreign_insurance_contracts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_insurance_contracts', 'comment')
    op.drop_constraint(None, 'foreign_immovable_properties', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_immovable_properties_financial_year_id_fkey'), 'foreign_immovable_properties', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_immovable_properties', 'comment')
    op.drop_constraint(None, 'foreign_financial_interests', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_financial_interests_financial_year_id_fkey'), 'foreign_financial_interests', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_financial_interests', 'comment')
    op.drop_constraint(None, 'foreign_equity_debt_interests', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_equity_debt_interests_financial_year_id_fkey'), 'foreign_equity_debt_interests', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_equity_debt_interests', 'comment')
    op.drop_constraint(None, 'foreign_depository_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_depository_accounts_financial_year_id_fkey'), 'foreign_depository_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_depository_accounts', 'comment')
    op.drop_constraint(None, 'foreign_deposit_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_deposit_custodial_accounts_financial_year_id_fkey'), 'foreign_deposit_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_deposit_custodial_accounts', 'comment')
    op.drop_column('foreign_deposit_custodial_accounts', 'hash_key')
    op.drop_constraint(None, 'foreign_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_custodial_accounts_financial_year_id_fkey'), 'foreign_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('foreign_custodial_accounts', 'comment')
    op.drop_constraint(None, 'financial_years', type_='foreignkey')
    op.create_foreign_key(op.f('financial_years_client_id_fkey'), 'financial_years', 'clients', ['client_id'], ['id'])
    op.add_column('employment', sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('employment', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employment', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employment', type_='foreignkey')
    op.create_foreign_key(op.f('employment_client_profile_id_fkey'), 'employment', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employment', 'client_id')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.create_foreign_key(op.f('dividends_quarter_id_fkey'), 'dividends', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_quarter_id_fkey'), 'comments', 'quarters', ['quarter_id'], ['id'])
    op.drop_column('clients', 'deactivated_at')
    op.drop_column('clients', 'is_active')
    op.drop_constraint(None, 'capital_gains', type_='foreignkey')
    op.create_foreign_key(op.f('capital_gains_quarter_id_fkey'), 'capital_gains', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'assets_disclosure_documents', type_='foreignkey')
    op.create_foreign_key(op.f('assets_disclosure_documents_financial_year_id_fkey'), 'assets_disclosure_documents', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('assets_disclosure_documents', 'is_reviewed')
    op.add_column('addresses', sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_client_profile_id_fkey'), 'addresses', 'client_profiles', ['client_profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('addresses', 'address_type',
               existing_type=sa.Enum('PRIMARY', 'SECONDARY', name='addresstype', native_enum=False),
               type_=postgresql.ENUM('Primary', 'Secondary', name='addresstype'),
               existing_nullable=False)
    op.drop_column('addresses', 'client_id')
    op.create_table('other_assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('maturity_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('maturity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('other_assets_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('other_assets_pkey'))
    )
    op.create_index(op.f('ix_other_assets_id'), 'other_assets', ['id'], unique=False)
    op.create_table('insurance',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sum_assured', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('premium_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tenure_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annuity_plan', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('annuity_receivable', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('annuity_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('annuity_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('insurance_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insurance_pkey'))
    )
    op.create_index(op.f('ix_insurance_id'), 'insurance', ['id'], unique=False)
    op.create_table('tax_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('jurisdiction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_three_returns_filed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('advanced_tax_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('filing_portal_credentials', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('outstanding_issues', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foreign_asset_reporting_india', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('foreign_asset_reporting_global', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('tax_records_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tax_records_pkey'))
    )
    op.create_index(op.f('ix_tax_records_id'), 'tax_records', ['id'], unique=False)
    op.create_index(op.f('ix_tax_records_financial_year_id'), 'tax_records', ['financial_year_id'], unique=False)
    op.create_table('client_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('social_security_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passport_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_citizenship', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previous_citizenship', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('residency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('power_of_attorney', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pep_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_huf', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('huf_pan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('huf_dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='client_profiles_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='client_profiles_pkey'),
    sa.UniqueConstraint('client_id', name='client_profiles_client_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_client_profiles_id'), 'client_profiles', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('cost_at_pv', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cost_at_pv_inr', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('goal_term', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('goals_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('goals_pkey'))
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('children_info',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('child_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('current_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('undergrad_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('postgrad_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('children_info_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('children_info_pkey'))
    )
    op.create_index(op.f('ix_children_info_id'), 'children_info', ['id'], unique=False)
    op.create_table('parent_assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_not_in_soa', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('parent_assets_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('parent_assets_pkey'))
    )
    op.create_index(op.f('ix_parent_assets_id'), 'parent_assets', ['id'], unique=False)
    op.create_table('soa_master',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('asset_class', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('allocation_self', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('allocation_spouse', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('allocation_parents', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_self_spouse', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('percent_within_type', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('percent_overall', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('soa_master_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('soa_master_pkey'))
    )
    op.create_index(op.f('ix_soa_master_id'), 'soa_master', ['id'], unique=False)
    op.create_index(op.f('ix_soa_master_financial_year_id'), 'soa_master', ['financial_year_id'], unique=False)
    op.create_table('loan_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('lender_issuer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('principal_outstanding', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('emi', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tenure_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('loan_records_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('loan_records_pkey'))
    )
    op.create_index(op.f('ix_loan_records_id'), 'loan_records', ['id'], unique=False)
    op.create_table('cp_advisors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('advisor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('jurisdiction', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('contact_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('relationship_timing', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expertise_area', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('cp_advisors_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cp_advisors_pkey'))
    )
    op.create_index(op.f('ix_cp_advisors_id'), 'cp_advisors', ['id'], unique=False)
    op.create_table('other_loans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('principal_outstanding', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('tenure_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate_of_interest', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deposit_against_loan', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('deposit_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('soa_line_item', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('other_loans_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('other_loans_pkey'))
    )
    op.create_index(op.f('ix_other_loans_id'), 'other_loans', ['id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('income_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gross_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('holder_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('incomes_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incomes_pkey'))
    )
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_index(op.f('ix_incomes_financial_year_id'), 'incomes', ['financial_year_id'], unique=False)
    op.create_table('real_estate_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plan_to_sell', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('year_to_sell', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('inheritance_share', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('soa_line_item', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('value_not_in_soa', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('real_estate_plans_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('real_estate_plans_pkey'))
    )
    op.create_index(op.f('ix_real_estate_plans_id'), 'real_estate_plans', ['id'], unique=False)
    op.create_table('cash_flow_office',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('home_loan_principal_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('emergency_fund_requirement', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('annual_fixed_expense', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('annual_variable_expense', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('annual_lifestyle_expense', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('arbitrage_fund_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('cash_flow_office_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_flow_office_pkey'))
    )
    op.create_index(op.f('ix_cash_flow_office_id'), 'cash_flow_office', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_office_financial_year_id'), 'cash_flow_office', ['financial_year_id'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('flow_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('cash_flows_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_flows_pkey'))
    )
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flows_financial_year_id'), 'cash_flows', ['financial_year_id'], unique=False)
    op.create_table('assets_with_maturity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('maturity_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('maturity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rate_of_interest', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount_in_soa', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('soa_line_item', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('income_earned', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cashflow_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('assets_with_maturity_client_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_with_maturity_pkey'))
    )
    op.create_index(op.f('ix_assets_with_maturity_id'), 'assets_with_maturity', ['id'], unique=False)
    op.create_table('rsu_vesting',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vesting_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('rsu_vesting_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rsu_vesting_pkey'))
    )
    op.create_index(op.f('ix_rsu_vesting_id'), 'rsu_vesting', ['id'], unique=False)
    op.create_index(op.f('ix_rsu_vesting_financial_year_id'), 'rsu_vesting', ['financial_year_id'], unique=False)
    op.drop_index(op.f('ix_residencies_id'), table_name='residencies')
    op.drop_table('residencies')
    op.drop_index(op.f('ix_personal_information_id'), table_name='personal_information')
    op.drop_table('personal_information')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_insurances_id'), table_name='insurances')
    op.drop_table('insurances')
    op.drop_index(op.f('ix_citizenships_id'), table_name='citizenships')
    op.drop_table('citizenships')
    # ### end Alembic commands ###
