"""empty message

Revision ID: 58241ac15c5d
Revises: 4e55d281118c
Create Date: 2026-01-06 11:46:52.119126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58241ac15c5d'
down_revision: Union[str, Sequence[str], None] = '4e55d281118c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_lookup_iso_country_code'), table_name='country_lookup')
    op.drop_index(op.f('ix_country_lookup_numeric_country_code'), table_name='country_lookup')
    op.drop_column('country_lookup', 'numeric_country_code')
    op.drop_column('country_lookup', 'iso_country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_lookup', sa.Column('iso_country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('country_lookup', sa.Column('numeric_country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_country_lookup_numeric_country_code'), 'country_lookup', ['numeric_country_code'], unique=False)
    op.create_index(op.f('ix_country_lookup_iso_country_code'), 'country_lookup', ['iso_country_code'], unique=False)
    # ### end Alembic commands ###
