"""empty message

Revision ID: 6afae6ab55fc
Revises: 06b8a01d8633
Create Date: 2025-12-27 15:50:32.583183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afae6ab55fc'
down_revision: Union[str, Sequence[str], None] = '06b8a01d8633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foreign_financial_interests', 'schedule_offered',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('foreign_immovable_properties', 'schedule_offered',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('foreign_other_capital_assets', 'schedule_offered',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('foreign_other_incomes', 'schedule_offered',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('foreign_signing_authority_accounts', 'schedule_offered',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foreign_signing_authority_accounts', 'schedule_offered',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('foreign_other_incomes', 'schedule_offered',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('foreign_other_capital_assets', 'schedule_offered',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('foreign_immovable_properties', 'schedule_offered',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('foreign_financial_interests', 'schedule_offered',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
