"""empty message

Revision ID: 6e726ae3fcb4
Revises: 
Create Date: 2026-01-14 12:14:31.570500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e726ae3fcb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_disclosure_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash', 'financial_year_id', name='uq_assets_doc_client_hash')
    )
    op.create_index(op.f('ix_assets_disclosure_documents_financial_year_id'), 'assets_disclosure_documents', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_assets_disclosure_documents_id'), 'assets_disclosure_documents', ['id'], unique=False)
    op.drop_constraint(op.f('capital_gains_client_id_fkey'), 'capital_gains', type_='foreignkey')
    op.drop_constraint(op.f('capital_gains_quarter_id_fkey'), 'capital_gains', type_='foreignkey')
    op.create_foreign_key(None, 'capital_gains', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'capital_gains', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cash_flow_office_financial_year_id_fkey'), 'cash_flow_office', type_='foreignkey')
    op.create_foreign_key(None, 'cash_flow_office', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cash_flows_financial_year_id_fkey'), 'cash_flows', type_='foreignkey')
    op.create_foreign_key(None, 'cash_flows', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_quarter_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dividends_quarter_id_fkey'), 'dividends', type_='foreignkey')
    op.drop_constraint(op.f('dividends_client_id_fkey'), 'dividends', type_='foreignkey')
    op.create_foreign_key(None, 'dividends', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dividends', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('financial_years_client_id_fkey'), 'financial_years', type_='foreignkey')
    op.create_foreign_key(None, 'financial_years', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_custodial_accounts_financial_year_id_fkey'), 'foreign_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_deposit_custodial_accounts_financial_year_id_fkey'), 'foreign_deposit_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_deposit_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_depository_accounts_financial_year_id_fkey'), 'foreign_depository_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_depository_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_equity_debt_interests_financial_year_id_fkey'), 'foreign_equity_debt_interests', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_equity_debt_interests', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_financial_interests_financial_year_id_fkey'), 'foreign_financial_interests', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_financial_interests', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_immovable_properties_financial_year_id_fkey'), 'foreign_immovable_properties', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_immovable_properties', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_insurance_contracts_financial_year_id_fkey'), 'foreign_insurance_contracts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_insurance_contracts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_other_capital_assets_financial_year_id_fkey'), 'foreign_other_capital_assets', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_other_capital_assets', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_other_incomes_financial_year_id_fkey'), 'foreign_other_incomes', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_other_incomes', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('foreign_signing_authority_accounts_financial_year_id_fkey'), 'foreign_signing_authority_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'foreign_signing_authority_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('incomes_financial_year_id_fkey'), 'incomes', type_='foreignkey')
    op.create_foreign_key(None, 'incomes', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interest_details_quarter_id_fkey'), 'interest_details', type_='foreignkey')
    op.drop_constraint(op.f('interest_details_client_id_fkey'), 'interest_details', type_='foreignkey')
    op.create_foreign_key(None, 'interest_details', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interest_details', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('jointly_owned_accounts_financial_year_id_fkey'), 'jointly_owned_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'jointly_owned_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('logins_client_id_fkey'), 'logins', type_='foreignkey')
    op.create_foreign_key(None, 'logins', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('other_income_client_id_fkey'), 'other_income', type_='foreignkey')
    op.drop_constraint(op.f('other_income_quarter_id_fkey'), 'other_income', type_='foreignkey')
    op.create_foreign_key(None, 'other_income', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'other_income', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quarters_financial_year_id_fkey'), 'quarters', type_='foreignkey')
    op.create_foreign_key(None, 'quarters', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('real_estate_financial_year_id_fkey'), 'real_estate', type_='foreignkey')
    op.create_foreign_key(None, 'real_estate', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rentals_quarter_id_fkey'), 'rentals', type_='foreignkey')
    op.drop_constraint(op.f('rentals_client_id_fkey'), 'rentals', type_='foreignkey')
    op.create_foreign_key(None, 'rentals', 'quarters', ['quarter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rentals', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rsu_vesting_financial_year_id_fkey'), 'rsu_vesting', type_='foreignkey')
    op.create_foreign_key(None, 'rsu_vesting', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('separately_owned_accounts_financial_year_id_fkey'), 'separately_owned_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'separately_owned_accounts', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('soa_master_financial_year_id_fkey'), 'soa_master', type_='foreignkey')
    op.create_foreign_key(None, 'soa_master', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_client_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tax_profile_client_id_fkey'), 'tax_profile', type_='foreignkey')
    op.drop_constraint(op.f('tax_profile_financial_year_id_fkey'), 'tax_profile', type_='foreignkey')
    op.create_foreign_key(None, 'tax_profile', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tax_profile', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tax_records_financial_year_id_fkey'), 'tax_records', type_='foreignkey')
    op.create_foreign_key(None, 'tax_records', 'financial_years', ['financial_year_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tax_records', type_='foreignkey')
    op.create_foreign_key(op.f('tax_records_financial_year_id_fkey'), 'tax_records', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'tax_profile', type_='foreignkey')
    op.drop_constraint(None, 'tax_profile', type_='foreignkey')
    op.create_foreign_key(op.f('tax_profile_financial_year_id_fkey'), 'tax_profile', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('tax_profile_client_id_fkey'), 'tax_profile', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_client_id_fkey'), 'tasks', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'soa_master', type_='foreignkey')
    op.create_foreign_key(op.f('soa_master_financial_year_id_fkey'), 'soa_master', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'separately_owned_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('separately_owned_accounts_financial_year_id_fkey'), 'separately_owned_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'rsu_vesting', type_='foreignkey')
    op.create_foreign_key(op.f('rsu_vesting_financial_year_id_fkey'), 'rsu_vesting', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.create_foreign_key(op.f('rentals_client_id_fkey'), 'rentals', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('rentals_quarter_id_fkey'), 'rentals', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'real_estate', type_='foreignkey')
    op.create_foreign_key(op.f('real_estate_financial_year_id_fkey'), 'real_estate', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'quarters', type_='foreignkey')
    op.create_foreign_key(op.f('quarters_financial_year_id_fkey'), 'quarters', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'other_income', type_='foreignkey')
    op.drop_constraint(None, 'other_income', type_='foreignkey')
    op.create_foreign_key(op.f('other_income_quarter_id_fkey'), 'other_income', 'quarters', ['quarter_id'], ['id'])
    op.create_foreign_key(op.f('other_income_client_id_fkey'), 'other_income', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'logins', type_='foreignkey')
    op.create_foreign_key(op.f('logins_client_id_fkey'), 'logins', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'jointly_owned_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('jointly_owned_accounts_financial_year_id_fkey'), 'jointly_owned_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.create_foreign_key(op.f('interest_details_client_id_fkey'), 'interest_details', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('interest_details_quarter_id_fkey'), 'interest_details', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.create_foreign_key(op.f('incomes_financial_year_id_fkey'), 'incomes', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_signing_authority_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_signing_authority_accounts_financial_year_id_fkey'), 'foreign_signing_authority_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_other_incomes', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_other_incomes_financial_year_id_fkey'), 'foreign_other_incomes', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_other_capital_assets', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_other_capital_assets_financial_year_id_fkey'), 'foreign_other_capital_assets', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_insurance_contracts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_insurance_contracts_financial_year_id_fkey'), 'foreign_insurance_contracts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_immovable_properties', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_immovable_properties_financial_year_id_fkey'), 'foreign_immovable_properties', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_financial_interests', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_financial_interests_financial_year_id_fkey'), 'foreign_financial_interests', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_equity_debt_interests', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_equity_debt_interests_financial_year_id_fkey'), 'foreign_equity_debt_interests', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_depository_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_depository_accounts_financial_year_id_fkey'), 'foreign_depository_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_deposit_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_deposit_custodial_accounts_financial_year_id_fkey'), 'foreign_deposit_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'foreign_custodial_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('foreign_custodial_accounts_financial_year_id_fkey'), 'foreign_custodial_accounts', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'financial_years', type_='foreignkey')
    op.create_foreign_key(op.f('financial_years_client_id_fkey'), 'financial_years', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.create_foreign_key(op.f('dividends_client_id_fkey'), 'dividends', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('dividends_quarter_id_fkey'), 'dividends', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_quarter_id_fkey'), 'comments', 'quarters', ['quarter_id'], ['id'])
    op.drop_constraint(None, 'cash_flows', type_='foreignkey')
    op.create_foreign_key(op.f('cash_flows_financial_year_id_fkey'), 'cash_flows', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'cash_flow_office', type_='foreignkey')
    op.create_foreign_key(op.f('cash_flow_office_financial_year_id_fkey'), 'cash_flow_office', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_constraint(None, 'capital_gains', type_='foreignkey')
    op.drop_constraint(None, 'capital_gains', type_='foreignkey')
    op.create_foreign_key(op.f('capital_gains_quarter_id_fkey'), 'capital_gains', 'quarters', ['quarter_id'], ['id'])
    op.create_foreign_key(op.f('capital_gains_client_id_fkey'), 'capital_gains', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_assets_disclosure_documents_id'), table_name='assets_disclosure_documents')
    op.drop_index(op.f('ix_assets_disclosure_documents_financial_year_id'), table_name='assets_disclosure_documents')
    op.drop_table('assets_disclosure_documents')
    # ### end Alembic commands ###
