"""empty message

Revision ID: 8fc2e418cf16
Revises: 02533cebd7c9
Create Date: 2026-01-28 12:28:58.215641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fc2e418cf16'
down_revision: Union[str, Sequence[str], None] = '02533cebd7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'address_type',
               existing_type=postgresql.ENUM('Primary', 'Secondary', name='addresstype'),
               type_=sa.Enum('PRIMARY', 'SECONDARY', name='addresstype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'address_type',
               existing_type=sa.Enum('PRIMARY', 'SECONDARY', name='addresstype', native_enum=False),
               type_=postgresql.ENUM('Primary', 'Secondary', name='addresstype'),
               existing_nullable=False)
    # ### end Alembic commands ###
