"""Updated file table

Revision ID: 9eb78404d762
Revises: b7323f49327c
Create Date: 2025-11-25 19:33:59.220497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb78404d762'
down_revision: Union[str, Sequence[str], None] = 'b7323f49327c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_login_id'), 'otp_verifications', ['login_id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_otp'), 'otp_verifications', ['otp'], unique=True)
    op.add_column('files', sa.Column('uploaded_by', sa.UUID(), nullable=False))
    op.add_column('files', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'uploaded_at')
    op.drop_column('files', 'uploaded_by')
    op.drop_index(op.f('ix_otp_verifications_otp'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_login_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
