"""empty message

Revision ID: 9f31082f846d
Revises: 6e726ae3fcb4
Create Date: 2026-01-14 14:22:32.490280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f31082f846d'
down_revision: Union[str, Sequence[str], None] = '6e726ae3fcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('capital_gains_client_id_fkey'), 'capital_gains', type_='foreignkey')
    op.create_foreign_key(None, 'capital_gains', 'clients', ['client_id'], ['id'])
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('dividends_client_id_fkey'), 'dividends', type_='foreignkey')
    op.create_foreign_key(None, 'dividends', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('interest_details_client_id_fkey'), 'interest_details', type_='foreignkey')
    op.create_foreign_key(None, 'interest_details', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('other_income_client_id_fkey'), 'other_income', type_='foreignkey')
    op.create_foreign_key(None, 'other_income', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('rentals_client_id_fkey'), 'rentals', type_='foreignkey')
    op.create_foreign_key(None, 'rentals', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.create_foreign_key(op.f('rentals_client_id_fkey'), 'rentals', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'other_income', type_='foreignkey')
    op.create_foreign_key(op.f('other_income_client_id_fkey'), 'other_income', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.create_foreign_key(op.f('interest_details_client_id_fkey'), 'interest_details', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dividends', type_='foreignkey')
    op.create_foreign_key(op.f('dividends_client_id_fkey'), 'dividends', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'deactivated_at')
    op.drop_column('clients', 'is_active')
    op.drop_constraint(None, 'capital_gains', type_='foreignkey')
    op.create_foreign_key(op.f('capital_gains_client_id_fkey'), 'capital_gains', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
