"""fix Advisor Table

Revision ID: a47a6fe0fdf9
Revises: e320bd6d93e7
Create Date: 2025-10-30 16:59:09.157200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47a6fe0fdf9'
down_revision: Union[str, Sequence[str], None] = 'e320bd6d93e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
