"""initial schema

Revision ID: b1911cf08f25
Revises: 
Create Date: 2026-01-09 12:43:41.939647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1911cf08f25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.create_table('country_lookup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_lookup_country_code'), 'country_lookup', ['country_code'], unique=False)
    op.create_index(op.f('ix_country_lookup_country_name'), 'country_lookup', ['country_name'], unique=False)
    op.create_index(op.f('ix_country_lookup_id'), 'country_lookup', ['id'], unique=False)
    op.create_table('documents_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subCategory', sa.String(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('is_password_protected', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_upload_id'), 'documents_upload', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('adhar_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_family_member', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('family_relationship', sa.String(), nullable=True),
    sa.Column('is_advance_tax_payer', sa.Boolean(), nullable=False),
    sa.Column('residence_type', sa.Enum('RES', 'NRI', 'NRO', name='residencetype'), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assigner_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('caller_name', sa.String(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('call_start_time', sa.DateTime(), nullable=True),
    sa.Column('call_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_phone_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'phone_number', name='uix_client_phone_mapping')
    )
    op.create_index(op.f('ix_client_phone_mappings_id'), 'client_phone_mappings', ['id'], unique=False)
    op.create_table('client_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('social_security_number', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('current_citizenship', sa.String(), nullable=True),
    sa.Column('previous_citizenship', sa.String(), nullable=True),
    sa.Column('residency', sa.String(), nullable=True),
    sa.Column('power_of_attorney', sa.Boolean(), nullable=True),
    sa.Column('pep_status', sa.Boolean(), nullable=True),
    sa.Column('is_huf', sa.Boolean(), nullable=True),
    sa.Column('huf_pan', sa.String(), nullable=True),
    sa.Column('huf_dob', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_profiles_id'), 'client_profiles', ['id'], unique=False)
    op.create_table('financial_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_years_id'), 'financial_years', ['id'], unique=False)
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', 'ADVISOR', name='userrole'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logins_id'), 'logins', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('is_parent_task', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('acceptance_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'TRANSFERRED', name='acceptance_status', native_enum=False), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('pause_date', sa.DateTime(), nullable=True),
    sa.Column('pause_reason', sa.String(), nullable=True),
    sa.Column('is_pending_on_client', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rejection_by', sa.Uuid(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('is_resource_requested', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('file_uploads', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejection_by'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_is_active'), 'tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('assets_with_maturity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('maturity_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('rate_of_interest', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('amount_in_soa', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('soa_line_item', sa.String(length=255), nullable=True),
    sa.Column('income_earned', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('cashflow_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_with_maturity_id'), 'assets_with_maturity', ['id'], unique=False)
    op.create_table('cash_flow_office',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('home_loan_principal_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('emergency_fund_requirement', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annual_fixed_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annual_variable_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annual_lifestyle_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('arbitrage_fund_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_office_financial_year_id'), 'cash_flow_office', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_office_id'), 'cash_flow_office', ['id'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flows_financial_year_id'), 'cash_flows', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_table('children_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('child_name', sa.String(length=255), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=True),
    sa.Column('undergrad_goal', sa.Text(), nullable=True),
    sa.Column('postgrad_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_info_id'), 'children_info', ['id'], unique=False)
    op.create_table('cp_advisors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('advisor_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('relationship_timing', sa.String(length=100), nullable=True),
    sa.Column('expertise_area', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_advisors_id'), 'cp_advisors', ['id'], unique=False)
    op.create_table('employment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('country_of_headquarter', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_id'), 'employment', ['id'], unique=False)
    op.create_table('foreign_custodial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('address_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code_of_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_opened_date', sa.Date(), nullable=True),
    sa.Column('peak_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_custodial_accounts_country_id'), 'foreign_custodial_accounts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_custodial_accounts_financial_year_id'), 'foreign_custodial_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_custodial_accounts_id'), 'foreign_custodial_accounts', ['id'], unique=False)
    op.create_table('foreign_deposit_custodial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('account_opened_during_tax_year', sa.Boolean(), nullable=True),
    sa.Column('account_closed_during_tax_year', sa.Boolean(), nullable=True),
    sa.Column('account_jointly_owned_with_spouse', sa.Boolean(), nullable=True),
    sa.Column('no_tax_item_reported', sa.Boolean(), nullable=True),
    sa.Column('maximum_value_during_tax_year', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('used_foreign_currency_exchange_rate', sa.Boolean(), nullable=True),
    sa.Column('foreign_currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('exchange_rate_source', sa.String(), nullable=True),
    sa.Column('name_of_financial_institution', sa.String(), nullable=True),
    sa.Column('giin', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('city_state_country_zip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_deposit_custodial_accounts_financial_year_id'), 'foreign_deposit_custodial_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_deposit_custodial_accounts_id'), 'foreign_deposit_custodial_accounts', ['id'], unique=False)
    op.create_table('foreign_depository_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('address_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code_of_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_opened_date', sa.Date(), nullable=True),
    sa.Column('peak_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance_dec', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance_march', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_depository_accounts_country_id'), 'foreign_depository_accounts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_depository_accounts_financial_year_id'), 'foreign_depository_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_depository_accounts_id'), 'foreign_depository_accounts', ['id'], unique=False)
    op.create_table('foreign_equity_debt_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_entity', sa.String(), nullable=True),
    sa.Column('address_of_entity', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('nature_of_entity', sa.String(), nullable=True),
    sa.Column('date_of_acquiring_the_interest', sa.Date(), nullable=True),
    sa.Column('initial_value_of_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('peak_value_of_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_value_of_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_gross_sale_proceeds', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_equity_debt_interests_country_id'), 'foreign_equity_debt_interests', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_equity_debt_interests_financial_year_id'), 'foreign_equity_debt_interests', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_equity_debt_interests_id'), 'foreign_equity_debt_interests', ['id'], unique=False)
    op.create_table('foreign_financial_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_entity', sa.String(), nullable=True),
    sa.Column('address_of_entity', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('nature_of_entity', sa.String(), nullable=True),
    sa.Column('nature_of_interest', sa.String(), nullable=True),
    sa.Column('date_since_held', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_accrued', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.String(), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_financial_interests_country_id'), 'foreign_financial_interests', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_financial_interests_financial_year_id'), 'foreign_financial_interests', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_financial_interests_id'), 'foreign_financial_interests', ['id'], unique=False)
    op.create_table('foreign_immovable_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('address_of_property', sa.String(), nullable=True),
    sa.Column('ownership_details', sa.String(), nullable=True),
    sa.Column('date_of_acquisition', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_derived_from_property', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.String(), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_immovable_properties_country_id'), 'foreign_immovable_properties', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_immovable_properties_financial_year_id'), 'foreign_immovable_properties', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_immovable_properties_id'), 'foreign_immovable_properties', ['id'], unique=False)
    op.create_table('foreign_insurance_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('address_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('date_of_contract', sa.Date(), nullable=True),
    sa.Column('cash_value_of_contract', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_gross_premium_paid', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_insurance_contracts_country_id'), 'foreign_insurance_contracts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_insurance_contracts_financial_year_id'), 'foreign_insurance_contracts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_insurance_contracts_id'), 'foreign_insurance_contracts', ['id'], unique=False)
    op.create_table('foreign_other_capital_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('name_of_asset', sa.String(), nullable=True),
    sa.Column('ownership_details', sa.String(), nullable=True),
    sa.Column('date_of_acquisition', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_derived_from_asset', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.String(), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_other_capital_assets_country_id'), 'foreign_other_capital_assets', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_capital_assets_financial_year_id'), 'foreign_other_capital_assets', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_capital_assets_id'), 'foreign_other_capital_assets', ['id'], unique=False)
    op.create_table('foreign_other_incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('name_of_person_derived_income', sa.String(), nullable=True),
    sa.Column('address_of_person_derived_income', sa.String(), nullable=True),
    sa.Column('income_derived_from_person', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('whether_taxable', sa.Boolean(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.String(), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_other_incomes_country_id'), 'foreign_other_incomes', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_incomes_financial_year_id'), 'foreign_other_incomes', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_incomes_id'), 'foreign_other_incomes', ['id'], unique=False)
    op.create_table('foreign_signing_authority_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code_of_institution', sa.String(), nullable=True),
    sa.Column('name_of_account_holder', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('peak_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_accrued_taxable', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_accrued_in_account', sa.Boolean(), nullable=True),
    sa.Column('amount_taxed_on_income', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.String(), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_signing_authority_accounts_country_id'), 'foreign_signing_authority_accounts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_signing_authority_accounts_financial_year_id'), 'foreign_signing_authority_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_signing_authority_accounts_id'), 'foreign_signing_authority_accounts', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cost_at_pv', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('cost_at_pv_inr', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('goal_term', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('income_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('holder_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_financial_year_id'), 'incomes', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_table('insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('sum_assured', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('premium_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('annuity_plan', sa.Boolean(), nullable=False),
    sa.Column('annuity_receivable', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annuity_start_date', sa.Date(), nullable=True),
    sa.Column('annuity_end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_id'), 'insurance', ['id'], unique=False)
    op.create_table('jointly_owned_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('maximum_account_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('type_of_account', sa.String(), nullable=True),
    sa.Column('financial_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country_code_name', sa.String(), nullable=True),
    sa.Column('joint_owners', sa.Integer(), nullable=True),
    sa.Column('principal_tin', sa.String(), nullable=True),
    sa.Column('tin_type', sa.String(), nullable=True),
    sa.Column('principal_last_name', sa.String(), nullable=True),
    sa.Column('principal_first_name', sa.String(), nullable=True),
    sa.Column('principal_address', sa.String(), nullable=True),
    sa.Column('principal_city', sa.String(), nullable=True),
    sa.Column('principal_zip', sa.String(), nullable=True),
    sa.Column('principal_country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jointly_owned_accounts_country_code_name'), 'jointly_owned_accounts', ['country_code_name'], unique=False)
    op.create_index(op.f('ix_jointly_owned_accounts_financial_year_id'), 'jointly_owned_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_jointly_owned_accounts_id'), 'jointly_owned_accounts', ['id'], unique=False)
    op.create_table('loan_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('lender_issuer', sa.String(length=255), nullable=True),
    sa.Column('principal_outstanding', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('emi', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_records_id'), 'loan_records', ['id'], unique=False)
    op.create_table('other_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('maturity_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_assets_id'), 'other_assets', ['id'], unique=False)
    op.create_table('other_loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('principal_outstanding', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('rate_of_interest', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deposit_against_loan', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('deposit_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('soa_line_item', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_loans_id'), 'other_loans', ['id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_login_id'), 'otp_verifications', ['login_id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_otp'), 'otp_verifications', ['otp'], unique=True)
    op.create_table('parent_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('value_not_in_soa', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_assets_id'), 'parent_assets', ['id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('keys_p256dh', sa.String(), nullable=False),
    sa.Column('keys_auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['logins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('quarters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('quarter_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_json_imported', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarters_id'), 'quarters', ['id'], unique=False)
    op.create_table('real_estate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('market_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('cost_of_acquisition', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('owners', sa.Text(), nullable=True),
    sa.Column('state_country', sa.String(length=255), nullable=True),
    sa.Column('loan_attached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_financial_year_id'), 'real_estate', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_real_estate_id'), 'real_estate', ['id'], unique=False)
    op.create_table('real_estate_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('plan_to_sell', sa.Boolean(), nullable=False),
    sa.Column('year_to_sell', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('inheritance_share', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('soa_line_item', sa.String(length=255), nullable=True),
    sa.Column('value_not_in_soa', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_plans_id'), 'real_estate_plans', ['id'], unique=False)
    op.create_table('rsu_vesting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('vesting_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsu_vesting_financial_year_id'), 'rsu_vesting', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_rsu_vesting_id'), 'rsu_vesting', ['id'], unique=False)
    op.create_table('separately_owned_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_code_name', sa.String(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('maximum_account_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('maximum_account_value_unknown', sa.Boolean(), nullable=True),
    sa.Column('type_of_account', sa.String(), nullable=True),
    sa.Column('name_of_financial_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('foreign_postal_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separately_owned_accounts_country_code_name'), 'separately_owned_accounts', ['country_code_name'], unique=False)
    op.create_index(op.f('ix_separately_owned_accounts_financial_year_id'), 'separately_owned_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_separately_owned_accounts_id'), 'separately_owned_accounts', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('session_start_time', sa.DateTime(), nullable=True),
    sa.Column('session_end_time', sa.DateTime(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_task_id'), 'sessions', ['task_id'], unique=False)
    op.create_table('soa_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('asset_class', sa.String(length=100), nullable=False),
    sa.Column('allocation_self', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('allocation_spouse', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('allocation_parents', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_self_spouse', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('percent_within_type', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('percent_overall', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soa_master_financial_year_id'), 'soa_master', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_soa_master_id'), 'soa_master', ['id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'advisor_id')
    )
    op.create_table('task_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_by', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('file_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_chat_messages_sender_id'), 'task_chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_task_chat_messages_task_id'), 'task_chat_messages', ['task_id'], unique=False)
    op.create_table('tax_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('expected_current_year_income', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('advance_tax_paid_Q1', sa.Float(), nullable=True),
    sa.Column('advance_tax_paid_Q2', sa.Float(), nullable=True),
    sa.Column('advance_tax_paid_Q3', sa.Float(), nullable=True),
    sa.Column('advance_tax_paid_Q4', sa.Float(), nullable=True),
    sa.Column('gross_salary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_profile_id'), 'tax_profile', ['id'], unique=False)
    op.create_table('tax_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('last_three_returns_filed', sa.Boolean(), nullable=True),
    sa.Column('advanced_tax_paid', sa.Boolean(), nullable=True),
    sa.Column('filing_portal_credentials', sa.String(), nullable=True),
    sa.Column('outstanding_issues', sa.String(), nullable=True),
    sa.Column('foreign_asset_reporting_india', sa.Boolean(), nullable=True),
    sa.Column('foreign_asset_reporting_global', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_records_financial_year_id'), 'tax_records', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tax_records_id'), 'tax_records', ['id'], unique=False)
    op.create_table('capital_gains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('ShortTermCG_15', sa.Float(), nullable=True),
    sa.Column('ShortTermCG_20', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ShortTermCG_At_Marginal_Rate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('LongTermCG_10', sa.Float(), nullable=True),
    sa.Column('LongTermCG_12_5', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('LongTermCG_20', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('NetShortTermGain20', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain12_5', sa.Float(), nullable=True),
    sa.Column('NetShortTermGainNormal', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain20', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain15', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain10', sa.Float(), nullable=True),
    sa.Column('ShortTermLossBroughtForward', sa.Float(), nullable=True),
    sa.Column('LongTermLossBroughtForward', sa.Float(), nullable=True),
    sa.Column('TotalLossBroughtForward', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain_15_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain_10_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain_20_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain_12_5_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain_20_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain_Normal_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('shortTermLossCarryForward', sa.Float(), nullable=True),
    sa.Column('longTermLossCarryForward', sa.Float(), nullable=True),
    sa.Column('cryptoCaptialGains', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capital_gains_id'), 'capital_gains', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('CAPITAL_GAINS', 'INTEREST_DETAILS', 'DIVIDENDS', 'RENTAL', 'OTHER_INCOME', 'SUMMARY', name='commentscategory'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('india_dividends', sa.Float(), nullable=True),
    sa.Column('foreign_dividends', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('ftc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.create_table('interest_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('fd_interest', sa.Float(), nullable=False),
    sa.Column('fd_tds', sa.Float(), nullable=False),
    sa.Column('savings_interest', sa.Float(), nullable=False),
    sa.Column('savings_tds', sa.Float(), nullable=False),
    sa.Column('other_interest', sa.Float(), nullable=False),
    sa.Column('other_tds', sa.Float(), nullable=False),
    sa.Column('pass_interest', sa.Float(), nullable=False),
    sa.Column('pass_tds', sa.Float(), nullable=False),
    sa.Column('epf_interest', sa.Float(), nullable=False),
    sa.Column('epf_tds', sa.Float(), nullable=False),
    sa.Column('it_refund_interest', sa.Float(), nullable=False),
    sa.Column('it_refund_tds', sa.Float(), nullable=False),
    sa.Column('foreign_interest', sa.Float(), nullable=True),
    sa.Column('foreign_interest_ftc', sa.Float(), nullable=True),
    sa.Column('total_interest', sa.Float(), nullable=False),
    sa.Column('total_tds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_details_id'), 'interest_details', ['id'], unique=False)
    op.create_table('other_income',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('income_44ad', sa.Float(), nullable=False),
    sa.Column('income_44ada', sa.Float(), nullable=False),
    sa.Column('consultancy_income', sa.Float(), nullable=False),
    sa.Column('consultancy_income_tds', sa.Float(), nullable=False),
    sa.Column('proceeds_insuarance_endowment', sa.Float(), nullable=False),
    sa.Column('proceeds_insuarance_endowment_tds', sa.Float(), nullable=False),
    sa.Column('taxable_proceeds_pfwithdrawal', sa.Float(), nullable=False),
    sa.Column('taxable_proceeds_pfwithdrawal_tds', sa.Float(), nullable=False),
    sa.Column('property_sale_tds', sa.Float(), nullable=False),
    sa.Column('additional_foreign_tax_credits', sa.Float(), nullable=False),
    sa.Column('employer_withheld_taxes', sa.Float(), nullable=False),
    sa.Column('tcs_on_remittance', sa.Float(), nullable=False),
    sa.Column('tcs_on_purchase_of_car', sa.Float(), nullable=False),
    sa.Column('tds_on_investments_goods_above_50L', sa.Float(), nullable=False),
    sa.Column('any_other_credits', sa.Float(), nullable=False),
    sa.Column('tds_44ad', sa.Float(), nullable=False),
    sa.Column('tds_44ada', sa.Float(), nullable=False),
    sa.Column('any_other_income', sa.Float(), nullable=False),
    sa.Column('tcs_expected', sa.Float(), nullable=False),
    sa.Column('tds_on_capital_gains', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_income_id'), 'other_income', ['id'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('annual_rental_income', sa.Float(), nullable=False),
    sa.Column('property_tax', sa.Float(), nullable=True),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('standard_deduction', sa.Float(), nullable=True),
    sa.Column('housing_loan_interest', sa.Float(), nullable=True),
    sa.Column('taxable_rental_income', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('region', sa.Enum('DOMESTIC', 'FOREIGN', name='region', native_enum=False), nullable=True),
    sa.Column('acquired_this_year', sa.Boolean(), nullable=False),
    sa.Column('transferred_this_year', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_id'), 'rentals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_id'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_other_income_id'), table_name='other_income')
    op.drop_table('other_income')
    op.drop_index(op.f('ix_interest_details_id'), table_name='interest_details')
    op.drop_table('interest_details')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_capital_gains_id'), table_name='capital_gains')
    op.drop_table('capital_gains')
    op.drop_index(op.f('ix_tax_records_id'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_financial_year_id'), table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_tax_profile_id'), table_name='tax_profile')
    op.drop_table('tax_profile')
    op.drop_index(op.f('ix_task_chat_messages_task_id'), table_name='task_chat_messages')
    op.drop_index(op.f('ix_task_chat_messages_sender_id'), table_name='task_chat_messages')
    op.drop_table('task_chat_messages')
    op.drop_table('task_assignees')
    op.drop_index(op.f('ix_soa_master_id'), table_name='soa_master')
    op.drop_index(op.f('ix_soa_master_financial_year_id'), table_name='soa_master')
    op.drop_table('soa_master')
    op.drop_index(op.f('ix_sessions_task_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_separately_owned_accounts_id'), table_name='separately_owned_accounts')
    op.drop_index(op.f('ix_separately_owned_accounts_financial_year_id'), table_name='separately_owned_accounts')
    op.drop_index(op.f('ix_separately_owned_accounts_country_code_name'), table_name='separately_owned_accounts')
    op.drop_table('separately_owned_accounts')
    op.drop_index(op.f('ix_rsu_vesting_id'), table_name='rsu_vesting')
    op.drop_index(op.f('ix_rsu_vesting_financial_year_id'), table_name='rsu_vesting')
    op.drop_table('rsu_vesting')
    op.drop_index(op.f('ix_real_estate_plans_id'), table_name='real_estate_plans')
    op.drop_table('real_estate_plans')
    op.drop_index(op.f('ix_real_estate_id'), table_name='real_estate')
    op.drop_index(op.f('ix_real_estate_financial_year_id'), table_name='real_estate')
    op.drop_table('real_estate')
    op.drop_index(op.f('ix_quarters_id'), table_name='quarters')
    op.drop_table('quarters')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_parent_assets_id'), table_name='parent_assets')
    op.drop_table('parent_assets')
    op.drop_index(op.f('ix_otp_verifications_otp'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_login_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_other_loans_id'), table_name='other_loans')
    op.drop_table('other_loans')
    op.drop_index(op.f('ix_other_assets_id'), table_name='other_assets')
    op.drop_table('other_assets')
    op.drop_index(op.f('ix_loan_records_id'), table_name='loan_records')
    op.drop_table('loan_records')
    op.drop_index(op.f('ix_jointly_owned_accounts_id'), table_name='jointly_owned_accounts')
    op.drop_index(op.f('ix_jointly_owned_accounts_financial_year_id'), table_name='jointly_owned_accounts')
    op.drop_index(op.f('ix_jointly_owned_accounts_country_code_name'), table_name='jointly_owned_accounts')
    op.drop_table('jointly_owned_accounts')
    op.drop_index(op.f('ix_insurance_id'), table_name='insurance')
    op.drop_table('insurance')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_financial_year_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_foreign_signing_authority_accounts_id'), table_name='foreign_signing_authority_accounts')
    op.drop_index(op.f('ix_foreign_signing_authority_accounts_financial_year_id'), table_name='foreign_signing_authority_accounts')
    op.drop_index(op.f('ix_foreign_signing_authority_accounts_country_id'), table_name='foreign_signing_authority_accounts')
    op.drop_table('foreign_signing_authority_accounts')
    op.drop_index(op.f('ix_foreign_other_incomes_id'), table_name='foreign_other_incomes')
    op.drop_index(op.f('ix_foreign_other_incomes_financial_year_id'), table_name='foreign_other_incomes')
    op.drop_index(op.f('ix_foreign_other_incomes_country_id'), table_name='foreign_other_incomes')
    op.drop_table('foreign_other_incomes')
    op.drop_index(op.f('ix_foreign_other_capital_assets_id'), table_name='foreign_other_capital_assets')
    op.drop_index(op.f('ix_foreign_other_capital_assets_financial_year_id'), table_name='foreign_other_capital_assets')
    op.drop_index(op.f('ix_foreign_other_capital_assets_country_id'), table_name='foreign_other_capital_assets')
    op.drop_table('foreign_other_capital_assets')
    op.drop_index(op.f('ix_foreign_insurance_contracts_id'), table_name='foreign_insurance_contracts')
    op.drop_index(op.f('ix_foreign_insurance_contracts_financial_year_id'), table_name='foreign_insurance_contracts')
    op.drop_index(op.f('ix_foreign_insurance_contracts_country_id'), table_name='foreign_insurance_contracts')
    op.drop_table('foreign_insurance_contracts')
    op.drop_index(op.f('ix_foreign_immovable_properties_id'), table_name='foreign_immovable_properties')
    op.drop_index(op.f('ix_foreign_immovable_properties_financial_year_id'), table_name='foreign_immovable_properties')
    op.drop_index(op.f('ix_foreign_immovable_properties_country_id'), table_name='foreign_immovable_properties')
    op.drop_table('foreign_immovable_properties')
    op.drop_index(op.f('ix_foreign_financial_interests_id'), table_name='foreign_financial_interests')
    op.drop_index(op.f('ix_foreign_financial_interests_financial_year_id'), table_name='foreign_financial_interests')
    op.drop_index(op.f('ix_foreign_financial_interests_country_id'), table_name='foreign_financial_interests')
    op.drop_table('foreign_financial_interests')
    op.drop_index(op.f('ix_foreign_equity_debt_interests_id'), table_name='foreign_equity_debt_interests')
    op.drop_index(op.f('ix_foreign_equity_debt_interests_financial_year_id'), table_name='foreign_equity_debt_interests')
    op.drop_index(op.f('ix_foreign_equity_debt_interests_country_id'), table_name='foreign_equity_debt_interests')
    op.drop_table('foreign_equity_debt_interests')
    op.drop_index(op.f('ix_foreign_depository_accounts_id'), table_name='foreign_depository_accounts')
    op.drop_index(op.f('ix_foreign_depository_accounts_financial_year_id'), table_name='foreign_depository_accounts')
    op.drop_index(op.f('ix_foreign_depository_accounts_country_id'), table_name='foreign_depository_accounts')
    op.drop_table('foreign_depository_accounts')
    op.drop_index(op.f('ix_foreign_deposit_custodial_accounts_id'), table_name='foreign_deposit_custodial_accounts')
    op.drop_index(op.f('ix_foreign_deposit_custodial_accounts_financial_year_id'), table_name='foreign_deposit_custodial_accounts')
    op.drop_table('foreign_deposit_custodial_accounts')
    op.drop_index(op.f('ix_foreign_custodial_accounts_id'), table_name='foreign_custodial_accounts')
    op.drop_index(op.f('ix_foreign_custodial_accounts_financial_year_id'), table_name='foreign_custodial_accounts')
    op.drop_index(op.f('ix_foreign_custodial_accounts_country_id'), table_name='foreign_custodial_accounts')
    op.drop_table('foreign_custodial_accounts')
    op.drop_index(op.f('ix_employment_id'), table_name='employment')
    op.drop_table('employment')
    op.drop_index(op.f('ix_cp_advisors_id'), table_name='cp_advisors')
    op.drop_table('cp_advisors')
    op.drop_index(op.f('ix_children_info_id'), table_name='children_info')
    op.drop_table('children_info')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_financial_year_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_cash_flow_office_id'), table_name='cash_flow_office')
    op.drop_index(op.f('ix_cash_flow_office_financial_year_id'), table_name='cash_flow_office')
    op.drop_table('cash_flow_office')
    op.drop_index(op.f('ix_assets_with_maturity_id'), table_name='assets_with_maturity')
    op.drop_table('assets_with_maturity')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_active'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_logins_id'), table_name='logins')
    op.drop_table('logins')
    op.drop_index(op.f('ix_financial_years_id'), table_name='financial_years')
    op.drop_table('financial_years')
    op.drop_index(op.f('ix_client_profiles_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_client_phone_mappings_id'), table_name='client_phone_mappings')
    op.drop_table('client_phone_mappings')
    op.drop_table('call_logs')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('files')
    op.drop_index(op.f('ix_documents_upload_id'), table_name='documents_upload')
    op.drop_table('documents_upload')
    op.drop_index(op.f('ix_country_lookup_id'), table_name='country_lookup')
    op.drop_index(op.f('ix_country_lookup_country_name'), table_name='country_lookup')
    op.drop_index(op.f('ix_country_lookup_country_code'), table_name='country_lookup')
    op.drop_table('country_lookup')
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.drop_table('advisors')
    # ### end Alembic commands ###
