"""Updated Task Table

Revision ID: b7323f49327c
Revises: c14c09f28a3a
Create Date: 2025-11-25 18:43:45.146489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7323f49327c'
down_revision: Union[str, Sequence[str], None] = 'c14c09f28a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
