"""new constants

Revision ID: bb8f5cc22a0d
Revises: f8636f10529a
Create Date: 2025-11-14 11:28:00.734616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8f5cc22a0d'
down_revision: Union[str, Sequence[str], None] = 'f8636f10529a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_by', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('file_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_chat_messages_sender_id'), 'task_chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_task_chat_messages_task_id'), 'task_chat_messages', ['task_id'], unique=False)
    op.alter_column('tasks', 'acceptance_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'TRANSFERRED', name='acceptance_status', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'acceptance_status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'TRANSFERRED', name='acceptance_status', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.drop_index(op.f('ix_task_chat_messages_task_id'), table_name='task_chat_messages')
    op.drop_index(op.f('ix_task_chat_messages_sender_id'), table_name='task_chat_messages')
    op.drop_table('task_chat_messages')
    # ### end Alembic commands ###
