"""empty message

Revision ID: be2b62f9ff0e
Revises: 2b1676b4d3c9
Create Date: 2026-02-02 11:28:00.965864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2b62f9ff0e'
down_revision: Union[str, Sequence[str], None] = '2b1676b4d3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_immovable_properties', sa.Column('sold_this_year', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foreign_immovable_properties', 'sold_this_year')
    # ### end Alembic commands ###
