"""add all models

Revision ID: ce6152cc8730
Revises: 7030dda7c212
Create Date: 2025-10-27 16:53:39.305184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6152cc8730'
down_revision: Union[str, Sequence[str], None] = '7030dda7c212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.create_table('documents_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subCategory', sa.String(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('is_password_protected', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_upload_id'), 'documents_upload', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('adhar_number', sa.String(), nullable=False),
    sa.Column('pan_number', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('is_family_member', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('family_relationship', sa.String(), nullable=False),
    sa.Column('is_advance_tax_payer', sa.Boolean(), nullable=False),
    sa.Column('residence_type', sa.Enum('RES', 'NORES', 'RNOR', name='residencetype'), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adhar_number'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('financial_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_years_id'), 'financial_years', ['id'], unique=False)
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ADVISOR', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_logins_id'), 'logins', ['id'], unique=False)
    op.create_table('quarters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('quarter_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_json_imported', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarters_id'), 'quarters', ['id'], unique=False)
    op.create_table('tax_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('previous_year_income', sa.Float(), nullable=False),
    sa.Column('expected_current_year_income', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('advance_tax_paid', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_profile_id'), 'tax_profile', ['id'], unique=False)
    op.create_table('capital_gains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('ShortTermCG_15', sa.Float(), nullable=True),
    sa.Column('ShortTermCG_20', sa.Float(), nullable=True),
    sa.Column('ShortTermCG_At_Marginal_Rate', sa.Float(), nullable=True),
    sa.Column('LongTermCG_10', sa.Float(), nullable=True),
    sa.Column('LongTermCG_12_5', sa.Float(), nullable=True),
    sa.Column('LongTermCG_20', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain20', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain12_5', sa.Float(), nullable=True),
    sa.Column('NetShortTermGainNormal', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain20', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain15', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain10', sa.Float(), nullable=True),
    sa.Column('ShortTermLossBroughtForward', sa.Float(), nullable=True),
    sa.Column('LongTermLossBroughtForward', sa.Float(), nullable=True),
    sa.Column('TotalLossBroughtForward', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain_15_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain_10_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain_20_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetLongTermGain_12_5_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain_20_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('NetShortTermGain_Normal_AfterSetoff', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capital_gains_id'), 'capital_gains', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'QUERY', 'CLARIFICATION', 'NOTE', name='commentscategory'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('india_dividends', sa.Float(), nullable=True),
    sa.Column('foreign_dividends', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('ftc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.create_table('interest_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_details_id'), 'interest_details', ['id'], unique=False)
    op.create_table('other_income',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('income_44ada', sa.Float(), nullable=False),
    sa.Column('property_sale_tds', sa.Float(), nullable=False),
    sa.Column('additional_foreign_tax_credits', sa.Float(), nullable=False),
    sa.Column('tcs_incurred', sa.Float(), nullable=False),
    sa.Column('tds_44ada', sa.Float(), nullable=False),
    sa.Column('salary_exemption', sa.Float(), nullable=False),
    sa.Column('any_other_income', sa.Float(), nullable=False),
    sa.Column('tcs_expected', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_income_id'), 'other_income', ['id'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('annual_rental_income', sa.Float(), nullable=False),
    sa.Column('property_tax', sa.Float(), nullable=True),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('standard_deduction', sa.Float(), nullable=True),
    sa.Column('housing_loan_interest', sa.Float(), nullable=True),
    sa.Column('taxable_rental_income', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_id'), 'rentals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_id'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_other_income_id'), table_name='other_income')
    op.drop_table('other_income')
    op.drop_index(op.f('ix_interest_details_id'), table_name='interest_details')
    op.drop_table('interest_details')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_capital_gains_id'), table_name='capital_gains')
    op.drop_table('capital_gains')
    op.drop_index(op.f('ix_tax_profile_id'), table_name='tax_profile')
    op.drop_table('tax_profile')
    op.drop_index(op.f('ix_quarters_id'), table_name='quarters')
    op.drop_table('quarters')
    op.drop_index(op.f('ix_logins_id'), table_name='logins')
    op.drop_table('logins')
    op.drop_index(op.f('ix_financial_years_id'), table_name='financial_years')
    op.drop_table('financial_years')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_documents_upload_id'), table_name='documents_upload')
    op.drop_table('documents_upload')
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.drop_table('advisors')
    # ### end Alembic commands ###
