"""empty message

Revision ID: d011c094f129
Revises: dfec8ebde807
Create Date: 2025-12-26 18:46:44.904186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd011c094f129'
down_revision: Union[str, Sequence[str], None] = 'dfec8ebde807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_lookup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_lookup_country_code'), 'country_lookup', ['country_code'], unique=False)
    op.create_index(op.f('ix_country_lookup_country_name'), 'country_lookup', ['country_name'], unique=False)
    op.create_index(op.f('ix_country_lookup_id'), 'country_lookup', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('assets_with_maturity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('maturity_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('rate_of_interest', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('amount_in_soa', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('soa_line_item', sa.String(length=255), nullable=True),
    sa.Column('income_earned', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('cashflow_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_with_maturity_id'), 'assets_with_maturity', ['id'], unique=False)
    op.create_table('children_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('child_name', sa.String(length=255), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=True),
    sa.Column('undergrad_goal', sa.Text(), nullable=True),
    sa.Column('postgrad_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_info_id'), 'children_info', ['id'], unique=False)
    op.create_table('client_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('social_security_number', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('current_citizenship', sa.String(), nullable=True),
    sa.Column('previous_citizenship', sa.String(), nullable=True),
    sa.Column('residency', sa.String(), nullable=True),
    sa.Column('power_of_attorney', sa.Boolean(), nullable=True),
    sa.Column('pep_status', sa.Boolean(), nullable=True),
    sa.Column('is_huf', sa.Boolean(), nullable=True),
    sa.Column('huf_pan', sa.String(), nullable=True),
    sa.Column('huf_dob', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_profiles_id'), 'client_profiles', ['id'], unique=False)
    op.create_table('cp_advisors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('relationship_timing', sa.String(length=100), nullable=True),
    sa.Column('expertise_area', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_advisors_id'), 'cp_advisors', ['id'], unique=False)
    op.create_table('employment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('country_of_headquarter', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_id'), 'employment', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cost_at_pv', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('cost_at_pv_inr', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('goal_term', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('sum_assured', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('premium_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('annuity_plan', sa.Boolean(), nullable=False),
    sa.Column('annuity_receivable', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annuity_start_date', sa.Date(), nullable=True),
    sa.Column('annuity_end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_id'), 'insurance', ['id'], unique=False)
    op.create_table('loan_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('lender_issuer', sa.String(length=255), nullable=True),
    sa.Column('principal_outstanding', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('emi', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_records_id'), 'loan_records', ['id'], unique=False)
    op.create_table('other_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('maturity_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_assets_id'), 'other_assets', ['id'], unique=False)
    op.create_table('other_loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('principal_outstanding', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('rate_of_interest', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deposit_against_loan', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('deposit_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('soa_line_item', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_loans_id'), 'other_loans', ['id'], unique=False)
    op.create_table('parent_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('value_not_in_soa', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_assets_id'), 'parent_assets', ['id'], unique=False)
    op.create_table('real_estate_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('plan_to_sell', sa.Boolean(), nullable=False),
    sa.Column('year_to_sell', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('inheritance_share', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('soa_line_item', sa.String(length=255), nullable=True),
    sa.Column('value_not_in_soa', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_plans_id'), 'real_estate_plans', ['id'], unique=False)
    op.create_table('cash_flow_office',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('home_loan_principal_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('emergency_fund_requirement', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annual_fixed_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annual_variable_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('annual_lifestyle_expense', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('arbitrage_fund_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_office_financial_year_id'), 'cash_flow_office', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_office_id'), 'cash_flow_office', ['id'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flows_financial_year_id'), 'cash_flows', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_table('foreign_custodial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('address_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code_of_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_opened_date', sa.Date(), nullable=True),
    sa.Column('peak_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_custodial_accounts_country_id'), 'foreign_custodial_accounts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_custodial_accounts_financial_year_id'), 'foreign_custodial_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_custodial_accounts_id'), 'foreign_custodial_accounts', ['id'], unique=False)
    op.create_table('foreign_depository_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_opened_date', sa.Date(), nullable=True),
    sa.Column('peak_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance_dec', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance_march', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_depository_accounts_country_id'), 'foreign_depository_accounts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_depository_accounts_financial_year_id'), 'foreign_depository_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_depository_accounts_id'), 'foreign_depository_accounts', ['id'], unique=False)
    op.create_table('foreign_equity_debt_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_entity', sa.String(), nullable=True),
    sa.Column('address_of_entity', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('nature_of_entity', sa.String(), nullable=True),
    sa.Column('date_of_acquiring_the_interest', sa.Date(), nullable=True),
    sa.Column('initial_value_of_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('peak_value_of_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('closing_value_of_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_interest', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_gross_sale_proceeds', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_equity_debt_interests_country_id'), 'foreign_equity_debt_interests', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_equity_debt_interests_financial_year_id'), 'foreign_equity_debt_interests', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_equity_debt_interests_id'), 'foreign_equity_debt_interests', ['id'], unique=False)
    op.create_table('foreign_financial_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_entity', sa.String(), nullable=True),
    sa.Column('address_of_entity', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('nature_of_entity', sa.String(), nullable=True),
    sa.Column('nature_of_interest', sa.String(), nullable=True),
    sa.Column('date_since_held', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_accrued', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_financial_interests_country_id'), 'foreign_financial_interests', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_financial_interests_financial_year_id'), 'foreign_financial_interests', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_financial_interests_id'), 'foreign_financial_interests', ['id'], unique=False)
    op.create_table('foreign_immovable_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('address_of_property', sa.String(), nullable=True),
    sa.Column('ownership_details', sa.String(), nullable=True),
    sa.Column('date_of_acquisition', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_derived_from_property', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_immovable_properties_country_id'), 'foreign_immovable_properties', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_immovable_properties_financial_year_id'), 'foreign_immovable_properties', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_immovable_properties_id'), 'foreign_immovable_properties', ['id'], unique=False)
    op.create_table('foreign_insurance_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('name_of_institution', sa.String(), nullable=True),
    sa.Column('address_of_institution', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('date_of_contract', sa.Date(), nullable=True),
    sa.Column('cash_value_of_contract', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_gross_premium_paid', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_insurance_contracts_country_id'), 'foreign_insurance_contracts', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_insurance_contracts_financial_year_id'), 'foreign_insurance_contracts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_insurance_contracts_id'), 'foreign_insurance_contracts', ['id'], unique=False)
    op.create_table('foreign_other_capital_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('name_of_asset', sa.String(), nullable=True),
    sa.Column('ownership_details', sa.String(), nullable=True),
    sa.Column('date_of_acquisition', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('income_derived_from_asset', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_other_capital_assets_country_id'), 'foreign_other_capital_assets', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_capital_assets_financial_year_id'), 'foreign_other_capital_assets', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_capital_assets_id'), 'foreign_other_capital_assets', ['id'], unique=False)
    op.create_table('foreign_other_incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('name_of_person_derived_income', sa.String(), nullable=True),
    sa.Column('address_of_person_derived_income', sa.String(), nullable=True),
    sa.Column('income_derived_from_person', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nature_of_income', sa.String(), nullable=True),
    sa.Column('whether_taxable', sa.Boolean(), nullable=True),
    sa.Column('income_taxable_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('schedule_offered', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('item_number_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_lookup.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_other_incomes_country_id'), 'foreign_other_incomes', ['country_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_incomes_financial_year_id'), 'foreign_other_incomes', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_foreign_other_incomes_id'), 'foreign_other_incomes', ['id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('income_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('holder_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_financial_year_id'), 'incomes', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_table('real_estate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('market_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('cost_of_acquisition', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('owners', sa.Text(), nullable=True),
    sa.Column('state_country', sa.String(length=255), nullable=True),
    sa.Column('loan_attached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_financial_year_id'), 'real_estate', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_real_estate_id'), 'real_estate', ['id'], unique=False)
    op.create_table('rsu_vesting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('vesting_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsu_vesting_financial_year_id'), 'rsu_vesting', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_rsu_vesting_id'), 'rsu_vesting', ['id'], unique=False)
    op.create_table('soa_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('asset_class', sa.String(length=100), nullable=False),
    sa.Column('allocation_self', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('allocation_spouse', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('allocation_parents', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_self_spouse', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('percent_within_type', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('percent_overall', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soa_master_financial_year_id'), 'soa_master', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_soa_master_id'), 'soa_master', ['id'], unique=False)
    op.create_table('tax_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('last_three_returns_filed', sa.Boolean(), nullable=True),
    sa.Column('advanced_tax_paid', sa.Boolean(), nullable=True),
    sa.Column('filing_portal_credentials', sa.String(), nullable=True),
    sa.Column('outstanding_issues', sa.String(), nullable=True),
    sa.Column('foreign_asset_reporting_india', sa.Boolean(), nullable=True),
    sa.Column('foreign_asset_reporting_global', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_records_financial_year_id'), 'tax_records', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tax_records_id'), 'tax_records', ['id'], unique=False)
    op.alter_column('call_logs', 'call_duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_call_logs_from_number'), 'call_logs', ['from_number'], unique=False)
    op.create_index(op.f('ix_call_logs_to_number'), 'call_logs', ['to_number'], unique=False)
    op.create_unique_constraint('uix_client_phone_mapping', 'client_phone_mappings', ['client_id', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_client_phone_mapping', 'client_phone_mappings', type_='unique')
    op.drop_index(op.f('ix_call_logs_to_number'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_from_number'), table_name='call_logs')
    op.alter_column('call_logs', 'call_duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_tax_records_id'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_financial_year_id'), table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_soa_master_id'), table_name='soa_master')
    op.drop_index(op.f('ix_soa_master_financial_year_id'), table_name='soa_master')
    op.drop_table('soa_master')
    op.drop_index(op.f('ix_rsu_vesting_id'), table_name='rsu_vesting')
    op.drop_index(op.f('ix_rsu_vesting_financial_year_id'), table_name='rsu_vesting')
    op.drop_table('rsu_vesting')
    op.drop_index(op.f('ix_real_estate_id'), table_name='real_estate')
    op.drop_index(op.f('ix_real_estate_financial_year_id'), table_name='real_estate')
    op.drop_table('real_estate')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_financial_year_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_foreign_other_incomes_id'), table_name='foreign_other_incomes')
    op.drop_index(op.f('ix_foreign_other_incomes_financial_year_id'), table_name='foreign_other_incomes')
    op.drop_index(op.f('ix_foreign_other_incomes_country_id'), table_name='foreign_other_incomes')
    op.drop_table('foreign_other_incomes')
    op.drop_index(op.f('ix_foreign_other_capital_assets_id'), table_name='foreign_other_capital_assets')
    op.drop_index(op.f('ix_foreign_other_capital_assets_financial_year_id'), table_name='foreign_other_capital_assets')
    op.drop_index(op.f('ix_foreign_other_capital_assets_country_id'), table_name='foreign_other_capital_assets')
    op.drop_table('foreign_other_capital_assets')
    op.drop_index(op.f('ix_foreign_insurance_contracts_id'), table_name='foreign_insurance_contracts')
    op.drop_index(op.f('ix_foreign_insurance_contracts_financial_year_id'), table_name='foreign_insurance_contracts')
    op.drop_index(op.f('ix_foreign_insurance_contracts_country_id'), table_name='foreign_insurance_contracts')
    op.drop_table('foreign_insurance_contracts')
    op.drop_index(op.f('ix_foreign_immovable_properties_id'), table_name='foreign_immovable_properties')
    op.drop_index(op.f('ix_foreign_immovable_properties_financial_year_id'), table_name='foreign_immovable_properties')
    op.drop_index(op.f('ix_foreign_immovable_properties_country_id'), table_name='foreign_immovable_properties')
    op.drop_table('foreign_immovable_properties')
    op.drop_index(op.f('ix_foreign_financial_interests_id'), table_name='foreign_financial_interests')
    op.drop_index(op.f('ix_foreign_financial_interests_financial_year_id'), table_name='foreign_financial_interests')
    op.drop_index(op.f('ix_foreign_financial_interests_country_id'), table_name='foreign_financial_interests')
    op.drop_table('foreign_financial_interests')
    op.drop_index(op.f('ix_foreign_equity_debt_interests_id'), table_name='foreign_equity_debt_interests')
    op.drop_index(op.f('ix_foreign_equity_debt_interests_financial_year_id'), table_name='foreign_equity_debt_interests')
    op.drop_index(op.f('ix_foreign_equity_debt_interests_country_id'), table_name='foreign_equity_debt_interests')
    op.drop_table('foreign_equity_debt_interests')
    op.drop_index(op.f('ix_foreign_depository_accounts_id'), table_name='foreign_depository_accounts')
    op.drop_index(op.f('ix_foreign_depository_accounts_financial_year_id'), table_name='foreign_depository_accounts')
    op.drop_index(op.f('ix_foreign_depository_accounts_country_id'), table_name='foreign_depository_accounts')
    op.drop_table('foreign_depository_accounts')
    op.drop_index(op.f('ix_foreign_custodial_accounts_id'), table_name='foreign_custodial_accounts')
    op.drop_index(op.f('ix_foreign_custodial_accounts_financial_year_id'), table_name='foreign_custodial_accounts')
    op.drop_index(op.f('ix_foreign_custodial_accounts_country_id'), table_name='foreign_custodial_accounts')
    op.drop_table('foreign_custodial_accounts')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_financial_year_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_cash_flow_office_id'), table_name='cash_flow_office')
    op.drop_index(op.f('ix_cash_flow_office_financial_year_id'), table_name='cash_flow_office')
    op.drop_table('cash_flow_office')
    op.drop_index(op.f('ix_real_estate_plans_id'), table_name='real_estate_plans')
    op.drop_table('real_estate_plans')
    op.drop_index(op.f('ix_parent_assets_id'), table_name='parent_assets')
    op.drop_table('parent_assets')
    op.drop_index(op.f('ix_other_loans_id'), table_name='other_loans')
    op.drop_table('other_loans')
    op.drop_index(op.f('ix_other_assets_id'), table_name='other_assets')
    op.drop_table('other_assets')
    op.drop_index(op.f('ix_loan_records_id'), table_name='loan_records')
    op.drop_table('loan_records')
    op.drop_index(op.f('ix_insurance_id'), table_name='insurance')
    op.drop_table('insurance')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_employment_id'), table_name='employment')
    op.drop_table('employment')
    op.drop_index(op.f('ix_cp_advisors_id'), table_name='cp_advisors')
    op.drop_table('cp_advisors')
    op.drop_index(op.f('ix_client_profiles_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_children_info_id'), table_name='children_info')
    op.drop_table('children_info')
    op.drop_index(op.f('ix_assets_with_maturity_id'), table_name='assets_with_maturity')
    op.drop_table('assets_with_maturity')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_country_lookup_id'), table_name='country_lookup')
    op.drop_index(op.f('ix_country_lookup_country_name'), table_name='country_lookup')
    op.drop_index(op.f('ix_country_lookup_country_code'), table_name='country_lookup')
    op.drop_table('country_lookup')
    # ### end Alembic commands ###
