"""add is_pending_on_client column

Revision ID: d033ec827c14
Revises: 0f5018ffe905
Create Date: 2025-12-03 12:44:01.285380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd033ec827c14'
down_revision: Union[str, Sequence[str], None] = '0f5018ffe905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('logins_email_key'), 'logins', type_='unique')
    op.drop_constraint(op.f('logins_mobile_number_key'), 'logins', type_='unique')
    op.drop_constraint(op.f('logins_username_key'), 'logins', type_='unique')
    op.add_column('tasks', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('pause_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'pause_date')
    op.drop_column('tasks', 'is_paused')
    op.create_unique_constraint(op.f('logins_username_key'), 'logins', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('logins_mobile_number_key'), 'logins', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('logins_email_key'), 'logins', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
