"""empty message

Revision ID: dfec8ebde807
Revises: 9d6bb41d1441
Create Date: 2025-12-26 18:44:04.128368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfec8ebde807'
down_revision: Union[str, Sequence[str], None] = '9d6bb41d1441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_logs', 'call_duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_call_logs_from_number'), 'call_logs', ['from_number'], unique=False)
    op.create_index(op.f('ix_call_logs_to_number'), 'call_logs', ['to_number'], unique=False)
    op.create_unique_constraint('uix_client_phone_mapping', 'client_phone_mappings', ['client_id', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_client_phone_mapping', 'client_phone_mappings', type_='unique')
    op.drop_index(op.f('ix_call_logs_to_number'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_from_number'), table_name='call_logs')
    op.alter_column('call_logs', 'call_duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
