"""New Table added

Revision ID: f8636f10529a
Revises: 1ba1b8b58441
Create Date: 2025-11-13 15:24:21.054886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8636f10529a'
down_revision: Union[str, Sequence[str], None] = '1ba1b8b58441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: task_assignees, shortTermLossCarryForward, longTermLossCarryForward 
    # and tax_profile columns are already created in 1ba1b8b58441
    # Convert Float columns to JSONB (Dict[str, float])
    # Since existing data is Float but model expects Dict, we convert to JSON object format
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "ShortTermCG_20" TYPE jsonb USING CASE WHEN "ShortTermCG_20" IS NULL THEN NULL::jsonb ELSE jsonb_build_object(\'value\', "ShortTermCG_20") END')
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "ShortTermCG_At_Marginal_Rate" TYPE jsonb USING CASE WHEN "ShortTermCG_At_Marginal_Rate" IS NULL THEN NULL::jsonb ELSE jsonb_build_object(\'value\', "ShortTermCG_At_Marginal_Rate") END')
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "LongTermCG_12_5" TYPE jsonb USING CASE WHEN "LongTermCG_12_5" IS NULL THEN NULL::jsonb ELSE jsonb_build_object(\'value\', "LongTermCG_12_5") END')
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "LongTermCG_20" TYPE jsonb USING CASE WHEN "LongTermCG_20" IS NULL THEN NULL::jsonb ELSE jsonb_build_object(\'value\', "LongTermCG_20") END')
    op.add_column('other_income', sa.Column('income_44ad', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('consultancy_income', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('consultancy_income_tds', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('proceeds_insuarance_endowment', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('proceeds_insuarance_endowment_tds', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('taxable_proceeds_pfwithdrawal', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('taxable_proceeds_pfwithdrawal_tds', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('employer_withheld_taxes', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('tcs_on_remittance', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('tcs_on_purchase_of_car', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('tds_on_investments_goods_above_50L', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('any_other_credits', sa.Float(), nullable=False))
    op.add_column('other_income', sa.Column('tds_44ad', sa.Float(), nullable=False))
    # Note: tds_on_capital_gains is already added in 1ba1b8b58441
    op.drop_column('other_income', 'salary_exemption')
    op.drop_column('other_income', 'tcs_incurred')
    # Note: tasks table structure (acceptance_status, rejection_reason, rejection_by, is_shared, due_date as DateTime)
    # is already created in 1ba1b8b58441, so no modifications needed here
    # Note: tax_profile columns are already modified in 1ba1b8b58441
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: tax_profile columns are handled in 1ba1b8b58441 downgrade
    # Note: tasks table structure is handled in 1ba1b8b58441 downgrade
    op.add_column('other_income', sa.Column('tcs_incurred', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('other_income', sa.Column('salary_exemption', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # Note: tds_on_capital_gains is handled in 1ba1b8b58441 downgrade
    op.drop_column('other_income', 'tds_44ad')
    op.drop_column('other_income', 'any_other_credits')
    op.drop_column('other_income', 'tds_on_investments_goods_above_50L')
    op.drop_column('other_income', 'tcs_on_purchase_of_car')
    op.drop_column('other_income', 'tcs_on_remittance')
    op.drop_column('other_income', 'employer_withheld_taxes')
    op.drop_column('other_income', 'taxable_proceeds_pfwithdrawal_tds')
    op.drop_column('other_income', 'taxable_proceeds_pfwithdrawal')
    op.drop_column('other_income', 'proceeds_insuarance_endowment_tds')
    op.drop_column('other_income', 'proceeds_insuarance_endowment')
    op.drop_column('other_income', 'consultancy_income_tds')
    op.drop_column('other_income', 'consultancy_income')
    op.drop_column('other_income', 'income_44ad')
    # Convert JSONB back to Float (extract value from dict or use the number directly)
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "LongTermCG_20" TYPE double precision USING CASE WHEN "LongTermCG_20" IS NULL THEN NULL WHEN jsonb_typeof("LongTermCG_20") = \'object\' THEN ("LongTermCG_20"->>\'value\')::double precision ELSE "LongTermCG_20"::text::double precision END')
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "LongTermCG_12_5" TYPE double precision USING CASE WHEN "LongTermCG_12_5" IS NULL THEN NULL WHEN jsonb_typeof("LongTermCG_12_5") = \'object\' THEN ("LongTermCG_12_5"->>\'value\')::double precision ELSE "LongTermCG_12_5"::text::double precision END')
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "ShortTermCG_At_Marginal_Rate" TYPE double precision USING CASE WHEN "ShortTermCG_At_Marginal_Rate" IS NULL THEN NULL WHEN jsonb_typeof("ShortTermCG_At_Marginal_Rate") = \'object\' THEN ("ShortTermCG_At_Marginal_Rate"->>\'value\')::double precision ELSE "ShortTermCG_At_Marginal_Rate"::text::double precision END')
    op.execute('ALTER TABLE capital_gains ALTER COLUMN "ShortTermCG_20" TYPE double precision USING CASE WHEN "ShortTermCG_20" IS NULL THEN NULL WHEN jsonb_typeof("ShortTermCG_20") = \'object\' THEN ("ShortTermCG_20"->>\'value\')::double precision ELSE "ShortTermCG_20"::text::double precision END')
    # Note: task_assignees, shortTermLossCarryForward, longTermLossCarryForward 
    # are handled in 1ba1b8b58441 downgrade
    # ### end Alembic commands ###
