"""Inital Commit from TSM

Revision ID: fbc5a0402c55
Revises: ea98e642b068
Create Date: 2025-10-29 15:08:00.867610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc5a0402c55'
down_revision: Union[str, Sequence[str], None] = 'ea98e642b068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assigner_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('is_parent_task', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('service_category', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('share_cc', sa.String(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.add_column('interest_details', sa.Column('fd_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('fd_tds', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('savings_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('savings_tds', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('other_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('other_tds', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('pass_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('pass_tds', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('epf_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('epf_tds', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('it_refund_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('it_refund_tds', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('total_interest', sa.Float(), nullable=False))
    op.add_column('interest_details', sa.Column('total_tds', sa.Float(), nullable=False))
    op.drop_column('interest_details', 'category')
    op.drop_column('interest_details', 'tds')
    op.drop_column('interest_details', 'amount')
    op.add_column('rentals', sa.Column('region', sa.Enum('DOMESTIC', 'FOREIGN', name='region', native_enum=False), nullable=True))
    op.add_column('rentals', sa.Column('acquired_this_year', sa.Boolean(), nullable=False))
    op.add_column('rentals', sa.Column('transferred_this_year', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'transferred_this_year')
    op.drop_column('rentals', 'acquired_this_year')
    op.drop_column('rentals', 'region')
    op.add_column('interest_details', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('interest_details', sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('interest_details', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('interest_details', 'total_tds')
    op.drop_column('interest_details', 'total_interest')
    op.drop_column('interest_details', 'it_refund_tds')
    op.drop_column('interest_details', 'it_refund_interest')
    op.drop_column('interest_details', 'epf_tds')
    op.drop_column('interest_details', 'epf_interest')
    op.drop_column('interest_details', 'pass_tds')
    op.drop_column('interest_details', 'pass_interest')
    op.drop_column('interest_details', 'other_tds')
    op.drop_column('interest_details', 'other_interest')
    op.drop_column('interest_details', 'savings_tds')
    op.drop_column('interest_details', 'savings_interest')
    op.drop_column('interest_details', 'fd_tds')
    op.drop_column('interest_details', 'fd_interest')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('notifications')
    # ### end Alembic commands ###
