"""empty message

Revision ID: ffb7d64c7e36
Revises: 58241ac15c5d
Create Date: 2026-01-06 11:47:35.369929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb7d64c7e36'
down_revision: Union[str, Sequence[str], None] = '58241ac15c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jointly_owned_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('maximum_account_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('type_of_account', sa.String(), nullable=True),
    sa.Column('financial_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country_code_name', sa.String(), nullable=True),
    sa.Column('joint_owners', sa.Integer(), nullable=True),
    sa.Column('principal_tin', sa.String(), nullable=True),
    sa.Column('tin_type', sa.String(), nullable=True),
    sa.Column('principal_last_name', sa.String(), nullable=True),
    sa.Column('principal_first_name', sa.String(), nullable=True),
    sa.Column('principal_address', sa.String(), nullable=True),
    sa.Column('principal_city', sa.String(), nullable=True),
    sa.Column('principal_zip', sa.String(), nullable=True),
    sa.Column('principal_country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jointly_owned_accounts_country_code_name'), 'jointly_owned_accounts', ['country_code_name'], unique=False)
    op.create_index(op.f('ix_jointly_owned_accounts_financial_year_id'), 'jointly_owned_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_jointly_owned_accounts_id'), 'jointly_owned_accounts', ['id'], unique=False)
    op.create_table('separately_owned_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_year_id', sa.UUID(), nullable=True),
    sa.Column('country_code_name', sa.String(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('maximum_account_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('maximum_account_value_unknown', sa.Boolean(), nullable=True),
    sa.Column('type_of_account', sa.String(), nullable=True),
    sa.Column('name_of_financial_institution', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('foreign_postal_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separately_owned_accounts_country_code_name'), 'separately_owned_accounts', ['country_code_name'], unique=False)
    op.create_index(op.f('ix_separately_owned_accounts_financial_year_id'), 'separately_owned_accounts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_separately_owned_accounts_id'), 'separately_owned_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_separately_owned_accounts_id'), table_name='separately_owned_accounts')
    op.drop_index(op.f('ix_separately_owned_accounts_financial_year_id'), table_name='separately_owned_accounts')
    op.drop_index(op.f('ix_separately_owned_accounts_country_code_name'), table_name='separately_owned_accounts')
    op.drop_table('separately_owned_accounts')
    op.drop_index(op.f('ix_jointly_owned_accounts_id'), table_name='jointly_owned_accounts')
    op.drop_index(op.f('ix_jointly_owned_accounts_financial_year_id'), table_name='jointly_owned_accounts')
    op.drop_index(op.f('ix_jointly_owned_accounts_country_code_name'), table_name='jointly_owned_accounts')
    op.drop_table('jointly_owned_accounts')
    # ### end Alembic commands ###
