# ITR filing persistence (separate from advance-tax coarse models).
# Import order: ITRReturn first (parent), then schedule + children.

from nucleus.models.itr_filling.audit_logging import (
    ITRActivityLog,
    ITRAuthAuditEvent,
    ITRFieldChangeSnapshot,
)
from nucleus.models.itr_filling.capital_gains import (
    ITRCGBondEntry,
    ITRCGExemption54,
    ITRCGExemption54F,
    ITRCGHPAcquisitionDetail,
    ITRCGHPBuyer,
    ITRCGHPEntry,
    ITRCGHPImprovement,
    ITRCGHPTransferExpense,
    ITRCGIndiaEQAndDebtMFBroker,
    ITRCGIndiaEQAndDebtMFTransaction,
    ITRCGSchedule,
    ITRCGUnlistedTransaction,
    ITRCGUSBroker,
    ITRCGUSTransaction,
    ITRCGVDATransaction,
)
from nucleus.models.itr_filling.cfl import (
    ITRCFLSchedule,
    ITRCFLSummary,
    ITRCFLYearEntry,
)
from nucleus.models.itr_filling.deductions import (
    ITRDed80C,
    ITRDed80DD80U,
    ITRDed80DDB,
    ITRDed80DDetail,
    ITRDed80DMeta,
    ITRDed80DPolicy,
    ITRDed80EEBLoan,
    ITRDed80ELoan,
    ITRDed80GDonation,
    ITRDed80GGAEntry,
    ITRDed80GGCEntry,
    ITRDed_80C_80CCD,
    ITRDedLoan,
    ITRDedOtherLine,
    ITRDedSchedule,
)
from nucleus.models.itr_filling.disclosures import (
    ITRALImmovableProperty,
    ITRALInvestment,
    ITRALMovableAsset,
    ITRDiscDirectorship,
    ITRDisclosuresSchedule,
    ITRDiscUnlistedShare,
    ITRFABankAccount,
    ITRFACashValueInsurance,
    ITRFAEquityDebt,
    ITRFAFinancialInterest,
    ITRFAForeignTrust,
    ITRFAImmovableProperty,
    ITRFAOtherAsset,
    ITRFAOtherForeignIncome,
    ITRFASigningAuthority,
)
from nucleus.models.itr_filling.house_property import (
    ITRHPCoOwner,
    ITRHPLoan,
    ITRHPProperty,
    ITRHPSchedule,
    ITRHPTenant,
)
from nucleus.models.itr_filling.itr_document import ITRDocument
from nucleus.models.itr_filling.itr_document_slot import ITRDocumentSlot
from nucleus.models.itr_filling.itr_return import ITRReturn
from nucleus.models.itr_filling.other_sources import (
    ITRDeemedIncome,
    ITROSBuybackShare,
    ITROSClubbingEntry,
    ITROSDividendDetail,
    ITROSIncomeLine,
    ITROSInterestDetail,
    ITROSOtherIncome,
    ITROSPTIEntity,
    ITROSSchedule,
    ITRTaxExemptIncome,
)
from nucleus.models.itr_filling.salary import (
    ITRForeignSalary,
    ITROtherSalary,
    ITRSalaryAllowance,
    ITRSalaryComponent,
    ITRSalaryEmployer,
    ITRSalaryPerquisite,
    ITRSalarySchedule,
)
from nucleus.models.itr_filling.tax_credits import (
    ITRAdvanceTaxPayment,
    ITRForm67Entry,
    ITRForm67Refund,
    ITRFSIEntry,
    ITRTaxCreditSchedule,
    ITRTCSEntry,
    ITRTDSNonSalary,
    ITRTDSProperty,
    ITRTDSSalary,
    ReliefClaimed,
)

__all__ = [
    "ITRReturn",
    # Salary (Schedule S)
    "ITRForeignSalary",
    "ITROtherSalary",
    "ITRSalaryAllowance",
    "ITRSalaryComponent",
    "ITRSalaryEmployer",
    "ITRSalaryPerquisite",
    "ITRSalarySchedule",
    # House Property (Schedule HP)
    "ITRHPCoOwner",
    "ITRHPLoan",
    "ITRHPProperty",
    "ITRHPSchedule",
    "ITRHPTenant",
    # Other Sources (Schedule OS)
    "ITROSBuybackShare",
    "ITROSClubbingEntry",
    "ITROSDividendDetail",
    "ITROSIncomeLine",
    "ITROSInterestDetail",
    "ITROSOtherIncome",
    "ITROSPTIEntity",
    "ITROSSchedule",
    # Deductions (Chapter VI-A)
    "ITRDedSchedule",
    "ITRDed80C",
    "ITRDed_80C_80CCD",
    "ITRDed80DDetail",
    "ITRDed80DMeta",
    "ITRDed80DPolicy",
    "ITRDed80GDonation",
    "ITRDed80DD80U",
    "ITRDed80DDB",
    "ITRDed80GGAEntry",
    "ITRDed80GGCEntry",
    "ITRDedLoan",
    "ITRDed80ELoan",
    "ITRDed80EEBLoan",
    "ITRDedOtherLine",
    # Tax credits
    "ITRAdvanceTaxPayment",
    "ITRForm67Entry",
    "ITRForm67Refund",
    "ITRFSIEntry",
    "ITRTCSEntry",
    "ITRTDSSalary",
    "ITRTDSNonSalary",
    "ITRTDSProperty",
    # Disclosures (AL / Part A / FA)
    "ITRALImmovableProperty",
    "ITRDiscDirectorship",
    "ITRDiscUnlistedShare",
    "ITRDisclosuresSchedule",
    "ITRFABankAccount",
    "ITRFACashValueInsurance",
    "ITRFAEquityDebt",
    "ITRFAFinancialInterest",
    "ITRFAForeignTrust",
    "ITRFAImmovableProperty",
    "ITRFAOtherAsset",
    "ITRFAOtherForeignIncome",
    "ITRFASigningAuthority",
    # Capital gains (Schedule CG)
    "ITRCGSchedule",
    "ITRCGIndiaEQAndDebtMFBroker",
    "ITRCGIndiaEQAndDebtMFTransaction",
    "ITRCGUSBroker",
    "ITRCGUSTransaction",
    "ITRCGUnlistedTransaction",
    "ITRCGBondEntry",
    "ITRCGHPEntry",
    "ITRCGHPAcquisitionDetail",
    "ITRCGHPImprovement",
    "ITRCGHPTransferExpense",
    "ITRCGHPBuyer",
    "ITRCGExemption54F",
    "ITRCGVDATransaction",
    "ITRCGExemption54",
    # Schedule CFL (carry forward of losses)
    "ITRCFLSchedule",
    "ITRCFLYearEntry",
    "ITRCFLSummary",
    # Audit / activity logging
    "ITRAuthAuditEvent",
    "ITRActivityLog",
    "ITRFieldChangeSnapshot",
    # Document upload slots
    "ITRDocumentSlot",
    "ITRDocument",
    "ITRALMovableAsset",
    "ITRALInvestment",
    "ReliefClaimed",
    "ITRTaxCreditSchedule",
    "ITRDeemedIncome",
    "ITRTaxExemptIncome",
]
